### ISSUE TITLE
Memory leak and high CPU using unw_step in libunwind-1.1-3

### ISSUE THREAD

**Issue by eoghanoh1** [libunwind/libunwind#103]
Build server OS: RHEL6.8
Deploy server OS: RHEL6.8
libunwind version: libunwind-1.1-3.el6.i686.rpm

The Application is 32bit, C++11, compiled with GCC7 and deployed on 64bit RHEL (v6.8). The libunwind library is being invoked by the Application on allocation and deallocation of memory within the Application to unwind the call stack, store details and use later for memory leak analysis.

The integration of libunwind into the Application code is as described in your documentation https://www.nongnu.org/libunwind/man/libunwind(3).html;

while (unw_step(&cursor) > 0) { }

To test the Application with libunwind, some light load was run through the Application.

Immediately it was obvious that there was a significant memory leak and CPU consumption for the Application was very high.

To narrow down the issue, I removed reading of registers from the while loop. The while loop is empty and contains no logic. The leak was still occurring.

I decided to put bounds on the while loop iterating only a certain number of times. I tested with 1 iteration, 2 iterations up to 5 iterations.

With 1 iteration of the while loop (one call to unw_step) the memory leak is not really visible (maybe very slight).
With 5 iterations of the while loop (five calls to unw_step) the memory leak is very noticeable and leaking quickly.

Note that with the while loop commented out (no call to unw_step()), the memory and CPU are stable.

Have you any idea of what the issue could be? Is it a known issue?

Second thing. I pulled down the latest version of libunwind source code (1.3.1) and tried to compiled for x86 so I could try this to see if the issue was resolved. 

I am building using;
./configure --target=i686-linux
make install

A couple of things, the *.so files that are built do not match up with the *.so that are installed by the libunwind-1.1-3.el6.i686.rpm.

v1.1-3 x86 installed libraries;
![image](https://user-images.githubusercontent.com/17784668/52409549-ad8ef400-2acd-11e9-8b35-810696b1d2bd.png)

v1.3.1 x86 build outputted libraries;
![image](https://user-images.githubusercontent.com/17784668/52409673-170f0280-2ace-11e9-9fc7-d6431cafdb0f.png)

The libunwind.so.8.0.1 and libunwind-coredump.so.0.0.0 are not generated in the i686 build at all.

If I build with x86_64 then these libraries are generated along with a lot of other libraries, likely related to the libunwind-devel package.

Any help would be appreciated.

Eoghan

**Comment by eoghanoh1** [comment]
With some changes to the Makefiles generated by ./configure (both top level Makefile and ./src/Makefile) I was able to build all the required the 32 bit .so's. To do this, post configure, I had to uncomment a number of lines in the Makefiles which were excluding the building of certain so's. Also in my case UNW_REMOTE_ONLY was being set - which was not what I wanted - that also had to be commented out.

With libunwind v1.3.1 - the memory leak I was seeing is gone. The CPU is still very high (same as it was on the previous version tested) - would you have any guidelines how or if the CPU consumption of libunwind can be decreased?

Some basic figures of what I mean by high CPU.

I run a standard load test frequently - this particular process usually operates at ~40-45% CPU when running top (so a little less than half a core being used).
I compile in libunwind into this process, reduce the load test rate to 1/14 the standard rate and the CPU  for the process is ~120-200% (3-5 times higher with 1/14th of the load).

I understand that extra CPU load will be placed on the process when introducing unwinding the call stack on every allocation and de-allocation of memory - however this difference is pretty significant.

Any information or guidance would be appreciated.

Thanks,
Eoghan

**Comment by milianw** [comment]
Just FYI: heaptrack may offer you a ready-made solution to heap memory profiling and leak detection.

That said, if CPU consumption is very high try to profile it with perf and see where the resources are being spent. Did you enable caching? Also, try to use `unw_backtrace` - it can be considerably faster than manual `unw_step` unwinding afair.

**Comment by Meteorix** [comment]
The same issue using the latest master. It slows my program 2 times when I am using `unw_step` every 0.01s. 
I have enabled the cache. I use remote unwinding, so cannot use `uwn_backtrace`. Any idea how can I optimize it?

**Comment by djwatson** [comment]
Sorry I'm trying to follow this discussion - is this a regression?  Have you tried to bisect?

**Comment by bregma** [comment]
libunwind 1.1 is pretty ancient and is no longer receiving support from developers. Is this still a problem with newer releases (libunwind 1.6 or later)?
