### ISSUE TITLE
ABI difference when compiling against glibc 2.28 vs 2.27

### ISSUE THREAD

**Issue by Erick555** [libunwind/libunwind#105]
Hello,
In [freedesktop-sdk ](https://gitlab.com/freedesktop-sdk) we maintain common software base for use by [flatpak](https://flatpak.org/) apps. We're trying to keep various elements like glibc or libunwind synced with latest upstream releases unless it would break ABI backward compatibility.

When trying [update glibc from 2.27 to 2.28](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/383) then rebuilding libunwind against the new version there is following ABI change detected by [libabigail](http://man7.org/linux/man-pages/man7/libabigail.7.html):
```
┌───────────────────────────────────────────────────┐
│ ABI Break: libunwind-x86_64.so.8:libunwind-x86_64 │
└───────────────────────────────────────────────────┘

Functions changes summary: 0 Removed, 1 Changed, 0 Added function
Variables changes summary: 0 Removed, 0 Changed, 0 Added variable

1 function with some indirect sub-type change:

  [C]'function int _Ux86_64_init_local(unw_cursor_t*, ucontext_t*)' at Ginit_local.c:42:1 has some indirect sub-type changes:
    parameter 2 of type 'ucontext_t*' has sub-type changes:
      in pointed to type 'struct ucontext_t' at ucontext.h:142:1:
        type size changed from 7488 to 7744 (in bits)
        1 data member insertion:
          'long long unsigned int ucontext_t::__ssp[4]', at offset 7488 (in bits) at ucontext.h:150:1
        no data member change (1 filtered);

┌─────────────────────────────────────┐
│ ABI Break: libunwind.so.8:libunwind │
└─────────────────────────────────────┘

Functions changes summary: 0 Removed, 1 Changed, 0 Added function
Variables changes summary: 0 Removed, 0 Changed, 0 Added variable

1 function with some indirect sub-type change:

  [C]'function int _ULx86_64_init_local(unw_cursor_t*, ucontext_t*)' at Ginit_local.c:42:1 has some indirect sub-type changes:
    parameter 2 of type 'ucontext_t*' has sub-type changes:
      in pointed to type 'struct ucontext_t' at ucontext.h:142:1:
        type size changed from 7488 to 7744 (in bits)
        1 data member insertion:
          'long long unsigned int ucontext_t::__ssp[4]', at offset 7488 (in bits) at ucontext.h:150:1
        no data member change (1 filtered);
```
I suppose it's caused by [this glibc commit](https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=25123a1c5c96429d70e75b85a9749b405909d7f2;hp=375a484459efcf2da1100e9ed228863be6665986) related to new Intel CET feature.

As libunwind developers, do you think this change could negatively affect backward ABI compatibility in practice?

Thanks for help.

**Comment by djwatson** [comment]
It looks like the shadow stack is added last, and libunwind won't use it in any way, so this should not be a problem.  We allow initializing a context from a ucontext_t, but not the other way, so at worst we'll truncate, but we don't use shadow stack for anything anyway.
