### ISSUE TITLE
Java Jemalloc / jeprof using libunwind pdf report doesn't show function names in linux

### ISSUE THREAD

**Issue by meiry** [libunwind/libunwind#108]
Hello all
trying here as jemalloc using libunwind or is much recommended by them , 
i compiled and static linked with jemalloc but still have the same problem where no function names has printed 
please take a look at this open issue i have in the jemalloc repository .
maybe someone had this problem already 
https://github.com/jemalloc/jemalloc/issues/1475
Thanks!

**Comment by djwatson** [comment]
I don't believe jemalloc uses libunwind to symbolize, I commented on the original task.
