### ISSUE TITLE
test-ptrace fails on s390x

### ISSUE THREAD

**Issue by sharkcz** [libunwind/libunwind#111]
I've tested the libunwind master branch on Fedora Rawhide (to-be F-31 with kernel 5.1rc3, gcc-9.0.1, glibc-2.29.9000, ...) and the ptrace test fails with following (libunwind has been configured with --enable-setjmp=no)
````
=============================================
   libunwind 1.4-rc1: tests/test-suite.log
=============================================

# TOTAL: 33
# PASS:  32
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test-ptrace
=================

Automated test (self,/bin/ls,/usr,(null))
FAILURE: unw_step() returned -8 for ip=3ff8d418826 (start ip=3ff8d41a4c8)
unwind failed with ret=-8
FAILURE: unw_step() returned -8 for ip=3ff8d41130e (start ip=3ff8d41a250)
unwind failed with ret=-8
FAILURE: unw_step() returned -8 for ip=3ff8d411388 (start ip=3ff8d41a4c8)
unwind failed with ret=-8
FAILURE: unw_step() returned -8 for ip=3ff8d418826 (start ip=3ff8d41a4c8)
unwind failed with ret=-8
FAILURE: unw_step() returned -8 for ip=3ff8d418826 (start ip=3ff8d41a4c8)
unwind failed with ret=-8
FAILURE: detected 10 errors
FAIL test-ptrace (exit status: 255)
````
cc: @mundaym

**Comment by sharkcz** [comment]
For the record - it fails in commit e1ca874882d3cd2f4c16440acf30f4eef89c7959 too, which is one of the initial commits adding s390x support.

**Comment by mundaym** [comment]
Thanks for reporting this, I'll take a look.

**Comment by mundaym** [comment]
I've tried to reproduce this using the latest fedora:rawhide docker container on an Ubuntu 18.04 host (Kernel: 4.15.0-20-generic) and the all the tests pass reliably, including `test-ptrace`. So it might be related to the kernel version. I'll see if I can get a proper Fedora image set up.

**Comment by sharkcz** [comment]
I've reproduced the issue on Fedora 28 with kernel 5.0.5.

**Comment by douglowe** [comment]
I have the exact same error on our system (CentOS Linux release 7.9.2009 (Core)). Did you find a fix for this failed test?

**Comment by mundaym** [comment]
I no longer work at IBM but @cwsolee may be able to help.

**Comment by sharkcz** [comment]
for the record - all tests are now passing on s390x (Fedora 34)

**Comment by douglowe** [comment]
@sharkcz - that is good to hear. Which version are you using (I'm trying v1.5.0)?

**Comment by sharkcz** [comment]
HEAD of the master branch

But when I run a CI job against the HEAD (on a different host, but still F-34 AFAIK), then I got 2 failures - `Gtest-trace` and  `Ltest-trace`. I haven't looked at the details yet.

**Comment by douglowe** [comment]
Thanks. I'll try a 1.6.0 release candidate then - see if that works for me.

**Comment by sharkcz** [comment]
aha, so the CI host is F-33 ...

and the failures are
````
FAIL: Gtest-trace
=================

FAILURE: detected 6 errors
FAILURE: unw_step() loop and unw_backtrace() depths differ: 3 vs. 5
FAILURE: unw_step() loop and backtrace() depths differ: 3 vs. 5
FAILURE: unw_step() loop and unw_backtrace() depths differ: 5 vs. 7
FAILURE: unw_step() loop and backtrace() depths differ: 5 vs. 7
FAILURE: unw_step() loop and unw_backtrace() depths differ: 5 vs. 7
FAILURE: unw_step() loop and backtrace() depths differ: 5 vs. 7
FAIL Gtest-trace (exit status: 255)

FAIL: Ltest-trace
=================

FAILURE: detected 6 errors
FAILURE: unw_step() loop and unw_backtrace() depths differ: 3 vs. 5
FAILURE: unw_step() loop and backtrace() depths differ: 3 vs. 5
FAILURE: unw_step() loop and unw_backtrace() depths differ: 5 vs. 7
FAILURE: unw_step() loop and backtrace() depths differ: 5 vs. 7
FAILURE: unw_step() loop and unw_backtrace() depths differ: 5 vs. 7
FAILURE: unw_step() loop and backtrace() depths differ: 5 vs. 7
FAIL Ltest-trace (exit status: 255)
````

**Comment by sharkcz** [comment]
Let's close this issue as all tests should be passing on a recent s390x system.
