### ISSUE TITLE
glibc: _U and _UL are reserved names

### ISSUE THREAD

**Issue by am11** [libunwind/libunwind#118]
On SmartOS (and probably other Solaris-likes), gcc (v7) throws the following error:

```sh
../include/libunwind-common.h:43:41: error: expected identifier or '(' before numeric constant
 # define UNW_PREFIX UNW_PASTE(UNW_PASTE(_U,UNW_TARGET),_)
                                         ^
../include/libunwind-common.h:35:25: note: in definition of macro 'UNW_PASTE2'
 #define UNW_PASTE2(x,y) x##y
                         ^
../include/libunwind-common.h:37:21: note: in expansion of macro 'UNW_PASTE'
 #define UNW_OBJ(fn) UNW_PASTE(UNW_PREFIX, fn)
                     ^~~~~~~~~
../include/libunwind-common.h:36:24: note: in expansion of macro 'UNW_PASTE2'
 #define UNW_PASTE(x,y) UNW_PASTE2(x,y)
                        ^~~~~~~~~~
../include/libunwind-common.h:43:21: note: in expansion of macro 'UNW_PASTE'
 # define UNW_PREFIX UNW_PASTE(UNW_PASTE(_U,UNW_TARGET),_)
                     ^~~~~~~~~
../include/libunwind-common.h:36:24: note: in expansion of macro 'UNW_PASTE2'
 #define UNW_PASTE(x,y) UNW_PASTE2(x,y)
                        ^~~~~~~~~~
../include/libunwind-common.h:43:31: note: in expansion of macro 'UNW_PASTE'
 # define UNW_PREFIX UNW_PASTE(UNW_PASTE(_U,UNW_TARGET),_)
                               ^~~~~~~~~
../include/libunwind-common.h:37:31: note: in expansion of macro 'UNW_PREFIX'
 #define UNW_OBJ(fn) UNW_PASTE(UNW_PREFIX, fn)
                               ^~~~~~~~~~
../include/tdep-x86_64/libunwind_i.h:211:41: note: in expansion of macro 'UNW_OBJ'
 #define tdep_trace                      UNW_OBJ(tdep_trace)
                                         ^~~~~~~
../include/tdep-x86_64/libunwind_i.h:260:12: note: in expansion of macro 'tdep_trace'
 extern int tdep_trace (unw_cursor_t *cursor, void **addresses, int *n);
            ^~~~~~~~~~
```

According to glibc manual (http://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html):

> In addition to the names documented in this manual, reserved names include all external identifiers (global functions and variables) that begin with an underscore (‘_’) and all identifiers regardless of use that begin with either two underscores <ins>or an underscore followed by a capital letter are reserved names</ins>. This is so that the library and header files can define functions, variables, and macros for internal purposes without risk of conflict with names in user programs.

There are two ways to fix this issue:

1. rename `_U` and `_UL` to something else (will also require changes in `tests/check-namespace.sh.in` file and other places?).
2. undefine `_U` explicitly:
    ```diff
    --- a/include/libunwind-common.h.in
    +++ b/include/libunwind-common.h.in
    @@ -23,6 +23,8 @@ LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
     OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
     WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.  */

    +#undef _U
    +
     #define UNW_VERSION_MAJOR      @PKG_MAJOR@
     #define UNW_VERSION_MINOR      @PKG_MINOR@
     #define UNW_VERSION_EXTRA      @PKG_EXTRA@
      ```

which approach is safe/better? If <span>#</span>1 is non-breaking-ABI, I would go for it (because <span>#</span>2 might have side effects).

**Comment by djwatson** [comment]
Unfortunately I think #1 breaks ABI.   #2 does seem hacky, but I can't think of anything better.

**Comment by am11** [comment]
Thank you, I think we can close this. Solaris initial changes are merged with `undef _U`: https://github.com/libunwind/libunwind/blob/0efe1db0ebf03ed8b7004c75c15cfd286854137f/include/libunwind-common.h.in#L33-L44
