### ISSUE TITLE
unw_get_proc_name can call an AS-unsafe function

### ISSUE THREAD

**Issue by loskutov** [libunwind/libunwind#123]
The documentation claims the following:
> unw_get_proc_name() is thread-safe. If cursor cp is in the local address-space, this routine is also safe to use from a signal handler.

However, invoking this function on an x86_64 Linux machine on a local-address-space cursor might lead to the following call stack:
```
#0  lzma_stream_buffer_decode (memlimit=0x7fffffffca40, flags=0, allocator=0x0, in=0x7fffbd3144d0 "\375\067zXZ", in_pos=0x7fffffffca48, in_size=915412, out=0x7fffbc936000 "", 
    out_pos=0x7fffffffca50, out_size=4470304) at ../../../../src/liblzma/common/stream_buffer_decoder.c:21
#1  0x00007ffff7f8017b in _Uelf64_extract_minidebuginfo (ei=0x7fffffffcb90, mdi=0x7fffffffcb00) at elfxx.c:278
#2  0x00007ffff7f80261 in _Uelf64_get_proc_name_in_image (as=0x7ffff7f892a0 <local_addr_space>, ei=0x7fffffffcb90, segbase=93824993083392, mapoff=851968, ip=93824994457837, 
    buf=0x7fffffffd110 "foo", buf_len=42, offp=0x7fffffffd108) at elfxx.c:320
#3  0x00007ffff7f80393 in _Uelf64_get_proc_name (as=0x7ffff7f892a0 <local_addr_space>, pid=6674, ip=93824994457837, buf=0x7fffffffd110 "foo", buf_len=42, offp=0x7fffffffd108) at elfxx.c:353
#4  0x00007ffff7f75b68 in get_static_proc_name (as=0x7ffff7f892a0 <local_addr_space>, ip=93824994457837, buf=0x7fffffffd110 "foo", buf_len=42, offp=0x7fffffffd108, arg=0x7fffffffc520)
    at x86_64/Ginit.c:249
#5  0x00007ffff7f7415b in get_proc_name (as=0x7ffff7f892a0 <local_addr_space>, ip=93824994457837, buf=0x7fffffffd110 "foo", buf_len=42, offp=0x7fffffffd108, arg=0x7fffffffc520)
    at mi/Gget_proc_name.c:93
#6  0x00007ffff7f741e8 in _ULx86_64_get_proc_name (cursor=0x7fffffffcd10, buf=0x7fffffffd110 "foo", buf_len=42, offp=0x7fffffffd108) at mi/Gget_proc_name.c:111
```
The `lzma_stream_buffer_decode` function doesn't give any AS-safety guarantees; moreover, it claims to allocate memory with `malloc`/`free` if `allocator=NULL` (which is the case). Hence, `unw_get_proc_name` is unsafe to use from a signal handler.

**Comment by djwatson** [comment]
I don't think there is any easy fix besides writing an async-safe lzma decoder?  Bummer.  We can pass an allocator if this improves the issue at all.

**Comment by loskutov** [comment]
Perhaps decompressing symbol tables shouldn't be enabled by default? MiniDebugInfo isn't such a common case, and sacrificing AS-safety for the sake of it is probably not worth the benefits.
