### ISSUE TITLE
Opt out of creating a weak alias for backtrace

### ISSUE THREAD

**Issue by pedronavf** [libunwind/libunwind#124]
libunwind creates a weak alias for backtrace unconditionally. On our application we write libc's backtrace and our own (previously using the _Unwind functions and now libunwind) so we have two pieces of info and to make sure our implementation doesn't have any bugs.

When calling libunwind functions from a signal handler when an invalid function dereference has happened (null pointer), libunwind crashes in `_ULarm_step`. Because of the alias the crash is happening when we call `backtrace_symbols_fd`, voiding our intent of having the system's backtrace written to disk before calling our own.

In the same way that we can configure without C++ exceptions `--disable-cxx-exceptions`(so the _Unwind functions are not aliased), I think the same should happen with `backtrace`

**Comment by acmorrow** [comment]
I'd expand this to not only making it not declare a weak alias, but to not declare the `backtrace` function at all. I'd like to be able to have a program that links to the system versions of both the libc and libunwind dynamic libraries, and then be able to call both the libc `backtrace` and the libunwind `unw_backtrace` functions. But if `libunwind` exports the `backtrace` symbol at all and ends up earlier in the link order than `libc` (which is likely), then calling `backtrace` will always be intercepted by `libunwind`. This makes it impossible, for instance, to write a meaningful comparative benchmark of libc `backtrace` vs `unw_backtrace`.

**Comment by pedronavf** [comment]
Yes, that's exactly what I was getting at! We want to be able to call both functions from our crash handler.

**Comment by acmorrow** [comment]
@pedronavf - Yes, in full agreement. I am currently in the process of refactoring a crash handler with an eye to moving to libunwind. For the crash handler, performance is rather uninteresting. But we have other uses of libc `backtrace` than just the crash handler, such as for a heap profiler and a heap debugger that captures deleter stacks, and in such cases the performance of the backtrace capture really does matter. We would like to be able to roll out the libunwind based crash handler without affecting the performance of the other `backtrace` callers until we have investigated the performance when they are switched over to libunwind. But we can't do that if libunwind unconditionally intercepts libc `backtrace` when it is linked into the process.

**Comment by pedronavf** [comment]
I ended up patching the library. I should probably work on a pull request.

This is the patch that removes the definition of `backtrace`
```
diff --git a/src/mi/backtrace.c b/src/mi/backtrace.c
index c7aa2bdc..80f6fecf 100644
--- a/src/mi/backtrace.c
+++ b/src/mi/backtrace.c
@@ -75,7 +75,7 @@ unw_backtrace (void **buffer, int size)
   return n;
 }
 
-extern int backtrace (void **buffer, int size)
-  WEAK ALIAS(unw_backtrace);
+//extern int backtrace (void **buffer, int size)
+//  WEAK ALIAS(unw_backtrace);
 
 #endif /* !UNW_REMOTE_ONLY */
```

Here's another one that removes libunwind's export of `unwind.h` which captures gcc's unwind functions and was giving me undefined symbols in some platforms (I believe it was in `_Unwind_GetIPInfo` in some ARM platforms that don't have it).


```
diff --git a/Makefile.am b/Makefile.am
index 8132fa4c..23002dde 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -46,7 +46,7 @@ include_HEADERS += include/libunwind-s390x.h
 endif
 
 if !REMOTE_ONLY
-include_HEADERS += include/libunwind.h include/unwind.h
+include_HEADERS += include/libunwind.h
 endif
 
 nodist_include_HEADERS = include/libunwind-common.h
```

**Comment by bertwesarg** [comment]
Have this in my branch for some time now, but didn't get to create a PR yet:

https://github.com/score-p/libunwind/commit/08976f1b8047cf75bda7ae9a3e4704b13c8cc065

**Comment by djwatson** [comment]
Sorry for late reply - seems fine to me if you want to send a PR.

**Comment by bertwesarg** [comment]
> Sorry for late reply - seems fine to me if you want to send a PR.

See #142

**Comment by djwatson** [comment]
merged.
