### ISSUE TITLE
Details on support for Alpine on PPC64LE

### ISSUE THREAD

**Issue by bharathappali** [libunwind/libunwind#125]
I have seen the table in `readme` stating that libunwind is available on `PPC64`.

I would like to know if it can be built / available on `PPC64LE (little endian)` for `alpine linux`.

In package page of alpine i could only see its [available](https://pkgs.alpinelinux.org/packages?name=libunwind&branch=edge&arch=x86_64) for `x86_64` architecture. I would like to know the [availability](https://pkgs.alpinelinux.org/packages?name=libunwind&branch=edge&arch=ppc64le) of it on `PPC64LE`

**Comment by bregma** [comment]
Looks like the binary package is available for your distribution.

We can't answer questions on particular binary distribution packages of the library since that is outside the scope of this project.
