### ISSUE TITLE
使用嵌入式ARM环境下栈空间消耗过大

### ISSUE THREAD

**Issue by RedPIGGER** [libunwind/libunwind#126]
在开发使用过程中，目前在ARM32位系统下unw_cursor_t是需要4K*4Byte=16KB的空间，如果一个系统中有100多个线程在运行，那么每个线程都是需要额外增加这16KB的空间来进行栈回溯操作，100个线程*16KB，大家想想这是需要消耗掉多大的栈内存空间，是否可以考虑ARM编译时确定这块栈空间合适的大小，总所周知，ARM芯片经常是运行在内存空间不那么充足的情况下，所以我觉得这个问题还是有必要进行讨论的，不知道大家中文能看懂吗*_*

**Comment by bertwesarg** [comment]
Offensichtlich kann Dave kein Chinesisch ;-)
