### ISSUE TITLE
libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE

### ISSUE THREAD

**Issue by amosbird** [libunwind/libunwind#138]
Hi, libunwind is used in my host application, which tries to dlopen a python runtime. When import `numpy`, it prints a very confusing error ` libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE`. What does it mean?

**Comment by amosbird** [comment]
The tracing log looks like this
```
libunwind: __register_frame(0x7f3f2e4e7078)
libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
libunwind: _Unwind_RaiseException(ex_obj=0x7f3f2fbf34e0)
libunwind: __unw_init_local(cursor=0x7ffdc8d9b1a0, context=0x7ffdc8d9b0f0)
libunwind: __unw_step(cursor=0x7ffdc8d9b1a0)
libunwind: unwind_phase1(ex_ojb=0x7f3f2fbf34e0): __unw_step() reached bottom => _URC_END_OF_STACK
libunwind: _Unwind_Resume_or_Rethrow(ex_obj=0x7f3f2fbf34e0), private_1=0
libunwind: _Unwind_RaiseException(ex_obj=0x7f3f2fbf34e0)
libunwind: __unw_init_local(cursor=0x7ffdc8d9a9d0, context=0x7ffdc8d9a920)
libunwind: __unw_step(cursor=0x7ffdc8d9a9d0)
libunwind: unwind_phase1(ex_ojb=0x7f3f2fbf34e0): __unw_step() reached bottom => _URC_END_OF_STACK
libunwind: __unw_init_local(cursor=0x7ffdc8d99170, context=0x7ffdc8d990c0)
libunwind: __unw_step(cursor=0x7ffdc8d99170)
libunwind: __unw_init_local(cursor=0x7f3ecb440970, context=0x7f3ecb4408c0)
libunwind: __unw_step(cursor=0x7f3ecb440970)

abort()
```

**Comment by MikeCamel** [comment]
Receiving the same error when running a Rust-generated wasmtime implementation. Any suggestions, please?

**Comment by wangyugui** [comment]
Hi,

'bad fde: FDE is really a CIE' still happen in tests of llvm 11.x branch.
https://github.com/llvm/llvm-project/commits/release/11.x


Command Output (stderr):
--
libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
libc++abi: terminating with uncaught exception of type int
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.  Program arguments: /ssd/git/os/llvm-project/build/bin/lli /ssd/git/os/llvm-project/llvm/test/ExecutionEngine/MCJIT/eh.ll
 #0 0x00000000011e1d6f llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/ssd/git/os/llvm-project/build/bin/lli+0x11e1d6f)
 #1 0x00000000011e0100 llvm::sys::RunSignalHandlers() (/ssd/git/os/llvm-project/build/bin/lli+0x11e0100)
 #2 0x00000000011e21c5 SignalHandler(int) (/ssd/git/os/llvm-project/build/bin/lli+0x11e21c5)
 #3 0x00007f889f258630 __restore_rt (/lib64/libpthread.so.0+0xf630)
 #4 0x00007f889e363387 raise (/lib64/libc.so.6+0x36387)
 #5 0x00007f889e364a78 abort (/lib64/libc.so.6+0x37a78)
 #6 0x00007f889f590bc6 (/ssd/git/os/llvm-project/build/bin/../lib/libc++abi.so.1+0x36bc6)
 #7 0x00007f889f573447 (/ssd/git/os/llvm-project/build/bin/../lib/libc++abi.so.1+0x19447)
 #8 0x00007f889f58fd83 std::__terminate(void (*)()) (/ssd/git/os/llvm-project/build/bin/../lib/libc++abi.so.1+0x35d83)
 #9 0x00007f889f592af6 (/ssd/git/os/llvm-project/build/bin/../lib/libc++abi.so.1+0x38af6)
#10 0x00007f889f592a90 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) (/ssd/git/os/llvm-project/build/bin/../lib/libc++abi.so.1+0x38a90)
#11 0x00007f889f68302d
/ssd/git/os/llvm-project/build/test/ExecutionEngine/MCJIT/Output/eh.ll.script: line 1: 54321 Aborted                 (core dumped) /ssd/git/os/llvm-project/build/bin/lli /ssd/git/os/llvm-project/llvm/test/ExecutionEngine/MCJIT/eh.ll

**Comment by milianw** [comment]
@wangyugui  please read the output you pasted and report that issue at the correct place (namely bugs.llvm.org). There's also a LLVM libunwind, but that has nothing directly to do with this lubunwind project here.

**Comment by wangyugui** [comment]
Now reported in https://bugs.llvm.org/show_bug.cgi?id=47799.
Thanks.
