### ISSUE TITLE
Question of C++ exception handling unwinder

### ISSUE THREAD

**Issue by expnkx** [libunwind/libunwind#139]
Why is destructor not called when the unwinder can't find the catch block of the exception?

AFAIK, the unwinder requires 2 phases of exception unwinding. The first step is to find the correct exception handler, second step is to unwind. Why can't exception unwinding be only 1 phase? Unwind + calling destructor no matter whether the exception catch block is found or not?

**Comment by djwatson** [comment]
Because if no exception handler is found, no destructors are ever called, by design - so that you can debug the exception. 

If someone wants to write a single phase unwind, I'm fine with that - but it's not the spec.

**Comment by expnkx** [comment]
> Because if no exception handler is found, no destructors are ever called, by design - so that you can debug the exception.
> 
> If someone wants to write a single phase unwind, I'm fine with that - but it's not the spec.

The problem is that a lot of people complain about the performance of exceptions when exception is thrown.

Maybe Herbception will be useful to solve the problem but I think current exceptions should be fixed to achieve better performance on at a bad path.
