### ISSUE TITLE
Provide unwind-config.cmake

### ISSUE THREAD

**Issue by NeroBurner** [libunwind/libunwind#143]
Please provide a `unwind-config.cmake` file to make usage of this library easier in cmake based projects. Currently projects need to create a FindUnwind.cmake or FindLibUnwind.cmake themselves (for example https://github.com/google/glog/blob/master/cmake/FindUnwind.cmake)

Furthermore I'd be interesting in creating a cmake project file to build the library with cmake instead of autotools, which by default does a out of source build. Has such a cmake-project any chance in getting accepted alongside the current autotool files?

**Comment by bertwesarg** [comment]
Does CMake based projects provide such files, so that non-CMake procjes can use these as dependencies? I'm not aware of such files. But if these `.cmake` files are also usable for non-CMake projects, than maybe thats the way to go. If not, I would preffer a build-system independ file. Back in the old days, this was `pkg-config`, but I'm getting old.

I personally include the install directory of libunwind to the `CMAKE_PREFIX_PATH`, which than works most of the time, I'm aware of.

**Comment by NeroBurner** [comment]
cmake can provide both, a cmake config and a pkg-config. The advantage of  a well written cmake-config is, that the resulting packages are relocatable. Which makes the lives of c++ package managers easier (for example [Hunter](https://github.com/cpp-pm/hunter))

**Comment by bertwesarg** [comment]
A non-comprehensive search revealed, that a _well written_ `pkg-config` file can also be relocatable. `pkg-config` knows the `--define-prefix` option:

```
  --define-prefix                         try to override the value of prefix for each .pc file found with a guesstimated value based on the location of the .pc file
```

Hopefully this is the default.

Tested here: https://github.com/tpn/pkg-config/blob/master/check/check-relocatable

So I would say, this is also possible with `pkg-config`.

**Comment by djwatson** [comment]
Generally, I'm in favor of cmake, and have moved most of my other projects to cmake.

However, at one point I did try to create a cmake build, and found it quite difficult - it's more difficult to get the same source files to build multiple times with different flags, necessary for local vs. remote builds, and many of the precise architecture checks we need are better supported in autotools vs cmake.  Cmake's advantages of nice cross-platform builds for osx and windows don't really help here, either.

Happy to review and consider any autotools/pkg-config changes, or if you want to prove me wrong with a full cmake change, go for it - but it would have to support everything the current autotools build does.
