### ISSUE TITLE
[mips]: missing symbols in static library

### ISSUE THREAD

**Issue by catalinvasile92** [libunwind/libunwind#145]
I tried using the libunwind-mips.a library, but when I try to link it with jemalloc (for example), I get that there are undefined symbols.

> octeon/port/usr/lib32/libjemalloc.so: undefined reference to `_Umips_getcontext'
> octeon/port/usr/lib32/libjemalloc.so: undefined reference to `_ULmips_get_reg'
> octeon/port/usr/lib32/libjemalloc.so: undefined reference to `_ULmips_init_local'
> octeon/port/usr/lib32/libjemalloc.so: undefined reference to `_ULmips_step'

I built the libunwind library the following way:

> ./autogen.sh
> ./configure --target=mips
> make

**Comment by djwatson** [comment]
What symbols exist in the libunwind-mips.a library?

**Comment by catalinvasile92** [comment]
I've attached the output for the following **nm -a ./src/.libs/libunwind-mips.a**.
[symbols.txt](https://github.com/libunwind/libunwind/files/3995368/symbols.txt)

**Comment by bregma** [comment]
Is this still an issue?
