### ISSUE TITLE
checking for ELF helper width... configure: error: Unknown ELF target: riscv64

### ISSUE THREAD

**Issue by tpgxyz** [libunwind/libunwind#151]
I'm trying to compile libunwind-1.3.1 on a riscv64 target. 
`BUILDSTDERR: checking for ELF helper width... configure: error: Unknown ELF target: riscv64`
More logs here:
https://abf.openmandriva.org/build_lists/671522

**Comment by kasperk81** [comment]
Fixed by #267.
