### ISSUE TITLE
dl_iterate_phdr not async signal safe

### ISSUE THREAD

**Issue by djwatson** [libunwind/libunwind#16]
The implementation of dl_iterate_phdr in glibc both takes locks, and allocates memory.  People hit this sporadically in production.   

Barring a fix in glibc, the best fix is probably an optionally linked library that will override dlopen, dlclose, and dl_iterate_phdr with a lock-free and non-mallocing cache.

**Comment by milianw** [comment]
As a first step, it would already be useful if there existed an API to feed libunwind with the information it needs. I.e. if the consumer application already overloads `dlopen` and `dlclose` it could notify libunwind accordingly and let it cache the `dl_iterate_phdr` state internally until the next `dl*` call comes in. Just want to mention this, not sure whether this is actually less work than what you propose which sounds even easier to use. Just please be careful not to break tools that rely on libunwind which also overload `dlopen` and `dlclose`.

**Comment by milianw** [comment]
One more comment: This whole idea, if done properly, will also lead to significant performance gains for heaptrack at least, since especially in a threaded applications the calls to `dl_iterate_phdr` have the highest performance impact when using libunwind currently.
