### ISSUE TITLE
Provide a way to disable symbol "backtrace" overring at configure time

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [libunwind/libunwind#163]
Hi,

It would be cool if at configure time we would have some kind of `./configure --disable-backtrace-symbol-override` which would have basically the same effect as this patch:

```
--- src/mi/backtrace.c
+++ src/mi/backtrace.c
@@ -75,7 +75,4 @@
   return n;
 }

-extern int backtrace (void **buffer, int size)
-  WEAK ALIAS(unw_backtrace);
-
 #endif /* !UNW_REMOTE_ONLY */
```

so that default (g)libc's backtrace symbol is not overriden by libunwind. I understand that most users want it overriden by default, but that may not be true for everyone (ie for us, for performance reasons). There are cases where we do want fast (but less accurate) backtraces, in which cases we would use the glibc one, and cases where we really do want accurate backtraces and care less about performances, for which libunwind is great (and has the symbol "unw_backtrace").

What do you think ?

Cheers,
Romain

**Comment by acmorrow** [comment]
I believe this was already done in #142

**Comment by Romain-Geissler-1A** [comment]
Ha indeed, I should have checked master first, I checked only the release 1.3.1 we use.

Are there plans to cut a new release in 2020 ?

**Comment by djwatson** [comment]
Release 1.4.0 && 1.5-rc1 cut.
