### ISSUE TITLE
Build issue with the musl C library on AAarch64

### ISSUE THREAD

**Issue by tpetazzoni** [libunwind/libunwind#176]
The build of libunwind 1.4.0 fails on AArch64 with the musl C library, with:
```
In file included from ../include/libunwind.h:7,
                 from ../include/libunwind_i.h:51,
                 from elfxx.h:33,
                 from elf64.h:7,
                 from elf64.c:2:
../include/libunwind-aarch64.h:195:2: error: unknown type name ‘__sigset_t’
  195 |  __sigset_t uc_sigmask;
      |  ^~~~~~~~~~
make[3]: *** [Makefile:3497: mi/Gdyn-extract.lo] Error 1
```
The Alpine Linux project has a patch that fixes the build issue: https://git.alpinelinux.org/aports/tree/main/libunwind/fix-aarch64-sigset_t.patch

**Comment by marv** [comment]
I just hit this problem as well trying to build a AArch64 system using musl. Would it be possible to get the fix for this into 1.5?

**Comment by sdmaclea** [comment]
The patch looks fine for glibc arm64 too IMO.

**Comment by djwatson** [comment]
I pulled the alpine linux patch in to both master and v1.5-stable.  Thanks
