### ISSUE TITLE
Support UNW_REMOTE_ONLY on Windows

### ISSUE THREAD

**Issue by sdmaclea** [libunwind/libunwind#180]
I have been working on a port of `libunwind` `UNW_REMOTE_ONLY` to `Windows`. This is the approach I have been taking.

1. Create a simple `Windows` to `Posix` platform abstraction layer.
2. Revise `UNW_REMOTE_ONLY` source code to allow ISO C or Windows compilation 
    + Use ISO variadic macros
    + Avoid statement expressions
    + Pad non-compliant empty structs
    + Work around compiler specific alignment, packing, and thread local storage.
    + Add mechanism to support HAVE_FETCH_AND_ADD
3. Disable warnings.
```cmake
    # Disable security warnings
    add_definitions(-D_CRT_SECURE_NO_WARNINGS) # Unsafe CRT warnings

    # Warnings in release builds
    add_compile_options(-wd4068) # ignore unknown pragma warnings (gcc pragmas)
    add_compile_options(-wd4146) # minus operator applied to unsigned
    add_compile_options(-wd4244) # possible loss of data implicit conversion
    add_compile_options(-wd4267) # possible loss of data implicit conversion
    add_compile_options(-wd4334) # 32-bit shift implicitly converted to 64 bits

    # Disable warning due to incorrect format specifier in debugging printf via the Debug macro
    add_compile_options(-wd4311) # pointer truncation from 'unw_word_t *' to 'long'
    add_compile_options(-wd4475) # 'fprintf' : length modifier 'L' cannot be used
    add_compile_options(-wd4477) # fprintf argument type
```

+ I will create a PR for item 2 above.
+ I can create a PR for item 1 (if it would be useful).
+ I could draft a PR to fix the warnings.  The Windows compiler is in pedantic mode, so it is reporting warning as errors unless disabled.
+ CoreCLR CMake is complicated and very app specific, so I am not sure it would be much use for your situation...

**Comment by djwatson** [comment]
Merged pull requests.
