### ISSUE TITLE
Not able to compile and install libunwind on macOS 10.13.3

### ISSUE THREAD

**Issue by mohitmv** [libunwind/libunwind#189]
I am getting following errors when I try to compile from source. 
```
In file included from mi/Gdestroy_addr_space.c:26:
../include/libunwind_i.h:64:3: error: Could not locate <elf.h>
# error Could not locate <elf.h>
  ^
../include/libunwind_i.h:94:5: error: Host has unknown byte-order.
#   error Host has unknown byte-order.
    ^
```

**Comment by djwatson** [comment]
I *think* this is usually provided by a kernel-headers package?  It's part of your system's distribution, in any case.

**Comment by mohitmv** [comment]
Why do you even need `elf.h` in mac ? 
ELF is linux specific executable format.
