### ISSUE TITLE
master fails on redhat 7.x due to NT_FILE

### ISSUE THREAD

**Issue by mwkrentel** [libunwind/libunwind#198]
The build for libunwind master fails on RedHat 7.x with an undefined
symbol `NT_FILE` in `src/coredump/_UCD_get_mapinfo_linux.c`.

RehHat 7.x uses glibc 2.17 and elf.h doesn't define NT_FILE.
linux/elf.h does, but not elf.h.

As a result, the build for master with default config options fails with:

```
../../libunwind/src/coredump/_UCD_get_mapinfo_linux.c: In function '_handle_file_note':
../../libunwind/src/coredump/_UCD_get_mapinfo_linux.c:70:17:
error: 'NT_FILE' undeclared (first use in this function); did you mean 'STT_FILE'?
```

This happens in master, but not 1.5-stable.

There are three obvious solutions.

1. make the code conditional on NT_FILE being defined.

2. include linux/elf.h in addition to elf.h, although I recommend
against this.  user programs normally should not include kernel
headers.

3. pull a copy of a current elf.h into the code base and include it.

@djwatson I think you should consider pulling a copy of a current
elf.h from elfutils or glibc into the code base.  There isn't really a
downside and that would allow libunwind to support newer features on
older systems, plus it would stop build failures like this.
But that's up to you.

**Comment by djwatson** [comment]
I have committed an ifdef guard for NT_FILE, let me know if this isn't enough to fix it. 

I will strongly consider pulling in a newer elf.h if we continue to run in to these issues, thanks.
