### ISSUE TITLE
Question about write_validate

### ISSUE THREAD

**Issue by theidexisted** [libunwind/libunwind#202]
I just had a benchmark and see that this function is on the hot path.

https://github.com/libunwind/libunwind/blob/master/src/x86_64/Ginit.c#L122

I am wondering that why we use two system call here, it seems that call read once is enough? Is there any potential improvement? thanks!

**Comment by djwatson** [comment]
IIRC there needs to be a matched read/write to drain the pipe.  Otherwise you will eventually block on a full pipe. 

I guess we could just close and reopen the pipe if it eventually gets full as an optimization?

**Comment by prehistoric-penguin** [comment]
I find a answer on SO:

https://stackoverflow.com/a/14437277/1292791

I had a benchmark and shows that the method on SO is quite faster if we open the _/dev/zero_ ahead. 
Can you judge whether the method in this answer is feasible?

**Comment by djwatson** [comment]
The original commit is 836c91c43d7a996028aa7e8d1f53630a6b8e7cbe

Yes, it appears we could just attempt a read from /dev/zero.  

However, we can't assume it is open, and we may have to re-open it, similar to the current pipe() code - for better or worse, a bunch of applications close all fds on fork manually. 

Would you like to submit a patch changing the pipe to a /dev/zero, and then removing the write() code?
