### ISSUE TITLE
libunwind-1.4.0 build failed for older linux version

### ISSUE THREAD

**Issue by mario-sz** [libunwind/libunwind#211]
we'd like to use libunwind-1.4.0, but it fails when compiling, as follows:

x86_64/Ginit.c:85:29: error: ‘O_CLOEXEC’ undeclared (first use in this function)
   pipe2 (mem_validate_pipe, O_CLOEXEC | O_NONBLOCK);

as our compile environment is too old to have pipe2 and O_CLOEXEC(linux 2.6.32，glibc 2.5)，but our product has to use this due to some historical reasons.

It works if I modify x86_64/Ginit.c as:
#ifndef O_CLOEXEC
   {
     int flags;
     pipe (mem_validate_pipe);
     flags = fcntl(mem_validate_pipe[0], F_GETFL);
     fcntl(mem_validate_pipe[0], F_SETFL, flags | O_NONBLOCK);
     fcntl(mem_validate_pipe[0], F_SETFD, FD_CLOEXEC);
     flags = fcntl(mem_validate_pipe[1], F_GETFL);
     fcntl(mem_validate_pipe[1], F_SETFL, flags | O_NONBLOCK);
     fcntl(mem_validate_pipe[1], F_SETFD, FD_CLOEXEC);
   }
 #else
   pipe2 (mem_validate_pipe, O_CLOEXEC | O_NONBLOCK);
 #endif
Is there any problem? or could you support older linux version which lacks pipe2 and O_CLOEXEC?

Best regards,

**Comment by djwatson** [comment]
It looks like pipe2 was added in 2008??  I don't think we should carry patches for 12 year old software in mainline, sorry.

Yes, this patch should work fine though if you want to carry it.
