### ISSUE TITLE
unable to build libunwind

### ISSUE THREAD

**Issue by Yadavdeepak007** [libunwind/libunwind#213]
i have run this following command .
git clone https://github.com/mxz297/libunwind.git libunwind
cd libunwind
mkdir install
./autogen.sh
./configure --prefix=`pwd`/install --enable-cxx-exceptions
make install -j4
But is error is coming -
config.status: error: cannot find input file: `tests/Makefile.in

**Comment by yuyichao** [comment]
Works for me. What's the full output. A brief search suggests that you either have something missing in your automake/autoconfig/whatever installation or some previous steps has failed.

Also, why are you using an older repo?
