### ISSUE TITLE
libunwind.h  is broken for clang on arm and aarch64

### ISSUE THREAD

**Issue by strejda** [libunwind/libunwind#215]
The local register variables are not supported by clang at all, and gcc states that these are can be used only if particular machine don’t provide sufficient control to select the desired register. See: https://gcc.gnu.org/onlinedocs/gcc/Local-Register-Variables.html

Fortunately this is not a case of your usage, so both cases should be converted to named register passed as input argument to following assembly block.

https://github.com/libunwind/libunwind/blob/7da31cd11e79af83ef93426c3760c36ff7631a7a/include/libunwind-aarch64.h#L229
https://github.com/libunwind/libunwind/blob/7da31cd11e79af83ef93426c3760c36ff7631a7a/include/libunwind-arm.h#L277

**Comment by djwatson** [comment]
Feel free to send a PR.

**Comment by bregma** [comment]
clang10 (release date 2020-03-24) accepts local register asm variables and appears to produce the correct code. Clang documents that it explicitly does not support global register asm variables, but that does not apply in this case.

I'm going to close this issue as "won't fix".
