### ISSUE TITLE
1.5.0 Release 

### ISSUE THREAD

**Issue by arlyon** [libunwind/libunwind#217]
Hi, sorry for the 'is it ready' post but I was wondering what the plans were for the 1.5 release candidates, and whether the release is on the order of weeks or months?

The only reason I ask is that 1.5 fixes some compilation issues for me and using conan, it would be nice to get the new version into the central package repo.

Thanks for the lib!

**Comment by djwatson** [comment]
I will try and roll 1.5 in the next week or two, there have been no new reported 1.5 issues in a while (but plenty on master).

**Comment by arlyon** [comment]
Thanks for the prompt reply, closing.

**Comment by djwatson** [comment]
I have tagged/uploaded release 1.5 here and savannah.  Thanks.

http://download.savannah.nongnu.org/releases/libunwind/
