### ISSUE TITLE
Configure step throws: error: Unknown ELF target: s390x

### ISSUE THREAD

**Issue by claudefalbriard** [libunwind/libunwind#22]
Trying to build the libunwind package from its source under the target architecture s390x (IBM system z) in order to full-fill a prerequisite for Julia language installation. The ./configure step throws the following messages: 

```
checking for sys/ptrace.h... (cached) yes
checking if we should build libunwind-ptrace... yes
checking if we should build libunwind-setjmp... yes
checking for build architecture... s390x
checking for host architecture... s390x
checking for target architecture... s390x
checking for target operating system... linux-gnu
checking for ELF helper width... configure: error: Unknown ELF target: s390x
```
Is it possible to add a support for this architecture to the libunwind, in a similar way as previously done for ppc64 machines?

**Comment by djwatson** [comment]
As far as I know libunwind does not support s390x.  It could definitely be done, and patches would be accepted.  This is the first I have heard of anyone using this platform though.

**Comment by djwatson** [comment]
Closing, but happy to accept patches for new arches.
