### ISSUE TITLE
Symbols missing when using ./configure --target=host and when --enable_debug_frame is set

### ISSUE THREAD

**Issue by aletru01** [libunwind/libunwind#237]
nm shows that those two symbols are undefined, it seems to happen when `./configure --target=host` is used and when `--enable_debug_frame` is set.
```
nm src/.libs/libunwind-aarch64.so.8.0.1
...
                 U _Uelf64_find_section
                 U _Uelf64_load_debuglink
...
```

This issue comes from the macro which is not set with `--target=host`
```
#ifndef UNW_REMOTE_ONLY
# include "elf64.h"
# include "elfxx.c"
#endif
```
The question is, is UNW_REMOTE_ONLY supposed to be set in --target=host mode? If that's the case maybe there should be a dependency on target==host for --enable-debug-frame. Or maybe the macro shouldn't be set?

**Comment by knjmooney** [comment]
UNW_REMOTE_ONLY is only ever set when target_arch != host_arch. If --enable-debug-frame doesn't work remotely, then you could disable it from building with the following in configure.ac
```
case "${target_arch}" in
  (arm) enable_debug_frame=yes;;
  (aarch64) enable_debug_frame=yes;;
  (*)   enable_debug_frame=no;;
esac])
+ if test xremote_only == xyes
+  enable_debug_frame=no;;
+ fi
```

**Comment by Boucher-Lambert** [comment]
Hi, this has been solved by https://github.com/libunwind/libunwind/pull/240/commits/d60f8b198e147d8ce67d8db65f3ad3b8897f9519
Can it be closed ?
