### ISSUE TITLE
tests: run-coredump-unwind: FAILURE: start IPs incorrect

### ISSUE THREAD

**Issue by JetXujing** [libunwind/libunwind#243]
Hello, I failed to run a test case using the latest libunwind package. The following information is displayed in the log file tests/test-suite.log:
=============================================
   libunwind 1.5-rc1: tests/test-suite.log
=============================================

# TOTAL: 37
# PASS:  36
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: run-coredump-unwind
=========================

FAILURE: start IPs incorrect
FAIL run-coredump-unwind (exit status: 255)

My procedure is as follows:
    1. download packages from https://codeload.github.com/libunwind/libunwind/zip/master and then unzip it
    2.  ./autogen.sh
    3. ./configure
    4. make
    5. make install
    6. make check

The following figure shows the running environment：
    gcc version: gcc (GCC) 7.3.0
    os: Linux x86_64

I try to locate the fault by myself and add the print information to the tests/test-coredump-unwind.c : main : 365:
    
![image](https://user-images.githubusercontent.com/43668249/110062673-ad44ae00-7da4-11eb-9336-ebbc0e695765.png)
and then rebuild and the same result is obtained. The log is as follows:
=============================================
   libunwind 1.5-rc1: tests/test-suite.log
=============================================

# TOTAL: 37
# PASS:  36
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: run-coredump-unwind
=========================

ret = 0, test_cur = 1
FAILURE: start IPs incorrect
FAIL run-coredump-unwind (exit status: 255)

According to the code, 0 is returned when unw_step is called for the first time.

I wonder if this is an environmental problem or a code problem, thanks.

**Comment by JetXujing** [comment]
it is environmental problem

**Comment by psandana** [comment]
> it is environmental problem

Hi @JetXujing , why do you say it is environmental problem. Can you elaborate? I have the same issue.

**Comment by JetXujing** [comment]
> > it is environmental problem
> 
> Hi @JetXujing , why do you say it is environmental problem. Can you elaborate? I have the same issue.

I try to reproduce on aarch64, it can't be reproduced, the test case run-coredump-unwind is passed.
