### ISSUE TITLE
Error when cross-compile for armhf

### ISSUE THREAD

**Issue by SKIYET** [libunwind/libunwind#252]
Dear

When I cross-compile libunwind for armhf, there is an error

> #10 252.0 libtool: link: arm-linux-gnueabihf-gcc -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -o Gperf-simple Gperf-simple.o  ../src/.libs/libunwind-arm.a /tmp/libunwind/src/.libs/libunwind.a ../src/.libs/libunwind.a -lc -lgcc_s
>#10 252.1 libtool: link: arm-linux-gnueabihf-gcc -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -o Lperf-simple Lperf-simple.o  ../src/.libs/libunwind.a -lc -lgcc_s
>#10 252.1 /bin/bash ../libtool  --tag=CC   --mode=link arm-linux-gnueabihf-gcc  -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__   -o Gperf-trace Gperf-trace.o ../src/libunwind-arm.la ../src/libunwind.la 
>#10 252.1 /bin/bash ../libtool  --tag=CC   --mode=link arm-linux-gnueabihf-gcc  -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__   -o Lperf-trace Lperf-trace.o ../src/libunwind.la 
>#10 252.2 libtool: link: arm-linux-gnueabihf-gcc -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -o Gperf-trace Gperf-trace.o  ../src/.libs/libunwind-arm.a /tmp/libunwind/src/.libs/libunwind.a ../src/.libs/libunwind.a -lc -lgcc_s
>#10 252.2 libtool: link: arm-linux-gnueabihf-gcc -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -o Lperf-trace Lperf-trace.o  ../src/.libs/libunwind.a -lc -lgcc_s
>#10 252.2 /usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: /tmp/libunwind/src/.libs/libunwind.a(Lex_tables.o): in function `arm_search_unwind_table':
>#10 252.2 /tmp/libunwind/src/arm/Gex_tables.c:388: multiple definition of `arm_search_unwind_table'; ../src/.libs/libunwind-arm.a(Gex_tables.o):/tmp/libunwind/src/arm/Gex_tables.c:388: first defined here
>#10 252.2 collect2: error: ld returned 1 exit status
>#10 252.2 make[1]: *** [Makefile:1155: Gperf-trace] Error 1
>#10 252.2 make[1]: *** Waiting for unfinished jobs....
>#10 252.2 make[1]: Leaving directory '/tmp/libunwind/tests'
>#10 252.2 make: *** [Makefile:604: all-recursive] Error 1

Can anyone help me?

**Comment by kasperk81** [comment]
Try the standalone steps:

```sh
docker run -it ubuntu:latest

apt update
apt install -y git automake make libtool-bin g++-arm-linux-gnueabihf

git clone https://github.com/libunwind/libunwind
cd libunwind
autoreconf -i

./configure --enable-shared \
    CC=arm-linux-gnueabihf-gcc \
    CXX=arm-linux-gnueabihf-g++ \
    --build=x86_64-linux-gnu \
    --host=arm-unknown-linux-gnueabihf > fulllog 2>&1

make
```

You can verify the output file with: `file src/.libs/libunwind.so.8.0.1 | fold`

> src/.libs/libunwind.so.8.0.1: ELF 32-bit LSB shared object, ARM, EABI5 version 1
 (SYSV), dynamically linked, BuildID[sha1]=56568c3cc7f856e44132450c19a29ea9481b9
07c, with debug_info, not stripped

**Comment by bregma** [comment]
The armhf-linux-gnu crosbuilds have been building fine for the last year or so. I'm closing this as no longer reproducible.
