### ISSUE TITLE
Wrong parsing of DWARF Common Information Entry version 4 and 5

### ISSUE THREAD

**Issue by koutheir** [libunwind/libunwind#256]
The function [`parse_cie()`](https://github.com/libunwind/libunwind/blob/19a2c01b1e8ac20871ea09d20f596d425ba53aed/src/dwarf/Gfde.c#L46) assumes that the DWARF Common Information Entry (CIE) structure being parsed follows format version 3 or below, because the CIE format version 4 introduces two new fields right after the `augmentation` (UTF-8 string) field:
- `address_size` (ubyte).
- `segment_size` (ubyte).

See section **6.4.1 Structure of Call Frame Information** of the [DWARF 4 specifications](http://www.dwarfstd.org/doc/DWARF4.pdf).

The CIE version check in [`parse_cie()`](https://github.com/libunwind/libunwind/blob/19a2c01b1e8ac20871ea09d20f596d425ba53aed/src/dwarf/Gfde.c#L120) is wrong because `DWARF_CIE_VERSION_MAX` is defined as `4` in [dwarf.h](https://github.com/libunwind/libunwind/blob/19a2c01b1e8ac20871ea09d20f596d425ba53aed/include/dwarf.h#L143).

This problem causes the parsing of a CIE version 4 structure to confuse the fields `code_alignment_factor (unsigned LEB128)` and `data_alignment_factor (signed LEB128)` for the fields `address_size` (ubyte) and `segment_size` (ubyte). This in turn results in garbage behavior when interpreting the instructions of the CIE.

The correct value of `DWARF_CIE_VERSION_MAX` should be `3`, in order to report an error when parsing CIE versions higher than 3, due to the additional fields.

**Comment by bregma** [comment]
Marking as closed by #266
