### ISSUE TITLE
Trouble building the package

### ISSUE THREAD

**Issue by dmitrypek** [libunwind/libunwind#261]
Hi, I am having trouble with basic package build. This is on Intel Xeon E5-2680v3, Linux CentOS, using Intel compilers v. 18.0.1.
I appreciate any help.

Here's my configure command:
 ./configure CC=icc CFLAGS="-g -O3 -ip -m64" CXX=icc CXXFLAGS=-m64 CCAS=gcc CCASFLAGS=-g     LDFLAGS="-L$PWD/src/.libs"

Here's output of make:

Making all in src
make[1]: Entering directory `/home/dmitry/libunwind/src'
make  all-am
make[2]: Entering directory `/home/dmitry/libunwind/src'
depbase=`echo os-linux.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CC   --mode=compile icc -DHAVE_CONFIG_H -I. -I../include  -I../include -I../include/tdep-x86_64 -I. -D_GNU_SOURCE -DNDEBUG  -g -O3 -ip -m64 -D__EXTENSIONS__ -MT os-linux.lo -MD -MP -MF $depbase.Tpo -c -o os-linux.lo os-linux.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  icc -DHAVE_CONFIG_H -I. -I../include -I../include -I../include/tdep-x86_64 -I. -D_GNU_SOURCE -DNDEBUG -g -O3 -ip -m64 -D__EXTENSIONS__ -MT os-linux.lo -MD -MP -MF .deps/os-linux.Tpo -c os-linux.c  -fPIC -DPIC -o .libs/os-linux.o
In file included from ../include/tdep-x86_64/libunwind_i.h(41),
                 from ../include/tdep/libunwind_i.h(25),
                 from ../include/libunwind_i.h(347),
                 from os-linux.c(30):
../include/dwarf.h(354): error: identifier "_Atomic" is undefined
      _Atomic uint32_t generation;        /* generation number */
      ^

In file included from ../include/tdep-x86_64/libunwind_i.h(41),
                 from ../include/tdep/libunwind_i.h(25),
                 from ../include/libunwind_i.h(347),
                 from os-linux.c(30):
../include/dwarf.h(354): error: expected a ";"
      _Atomic uint32_t generation;        /* generation number */
                       ^

In file included from ../include/tdep/libunwind_i.h(25),
                 from ../include/libunwind_i.h(347),
                 from os-linux.c(30):
../include/tdep-x86_64/libunwind_i.h(69): error: identifier "_Atomic" is undefined
      _Atomic uint32_t cache_generation;
      ^

In file included from ../include/tdep/libunwind_i.h(25),
                 from ../include/libunwind_i.h(347),
                 from os-linux.c(30):
../include/tdep-x86_64/libunwind_i.h(69): error: expected a ";"
      _Atomic uint32_t cache_generation;
                       ^

compilation aborted for os-linux.c (code 2)
make[2]: *** [os-linux.lo] Error 1
make[2]: Leaving directory `/home/dmitry/libunwind/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/dmitry/libunwind/src'
make: *** [all-recursive] Error 1

**Comment by kasperk81** [comment]
in gcc/clang, c11 features get implicitly enabled with gnu extension, but not with icc.
add `-std=c11` to your CFLAGS:

`./configure CC=icc CFLAGS=" -std=c11 -g -O3 -ip -m64" CXX=icc CXXFLAGS=-m64 CCAS=gcc CCASFLAGS=-g LDFLAGS="-L$PWD/src/.libs"`
