### ISSUE TITLE
x86_64 registers have incorrect values during CFI/CFA calculations

### ISSUE THREAD

**Issue by tmshort** [libunwind/libunwind#263]
Some assembly code (e.g. OpenSSL's `bn_mul_mont()` and `bn_mult_mont_gather5()`) uses CFI/CFA expressions that are somewhat complicated, in that they use multiple registers in the calculation.

In this case, running libunwind periodically via a signal is used to determine where in the code the system is spending its time. Since OpenSSL has a number of functions that can take a while, they are vulnerable to being interrupted by this signal.

While doing these calculations, it appears that some of the registers used have incorrect values. However, `gdb` is able to complete a backtrace.

Example:
In OpenSSL_1_1_1-stable, crypto/bn/asm/x86_64-mont.pl (source of `bn_mul_mont()`) there is the following CFI/CFA expression:
```
.cfi_cfa_expression        %rsp+8,$num,8,mul,plus,deref,+8
```
If `unw_backtrace()` is called (via a signal for instance) and it attempts to run the calculation over the expression, a segfault happens. Here is the output (tweaked to include values) via `UNW_DEBUG_LEVEL=15`:
(Note that `%r7` is an alias to `%rsp` and `$num` is `%r9`.)
```
              >_ULx86_64_dwarf_eval_expr: len=10, pushing initial value=0x0
               >_ULx86_64_dwarf_eval_expr: push -> 0x0
               >_ULx86_64_dwarf_eval_expr: OP_breg(r7,0x8)
               >_ULx86_64_dwarf_eval_expr: push -> 0x7ffdbe4e8c08
               >_ULx86_64_dwarf_eval_expr: OP_breg(r9,0x0)
               >_ULx86_64_dwarf_eval_expr: push -> 0x7ffdbe4e7590
               >_ULx86_64_dwarf_eval_expr: OP_lit(8)
               >_ULx86_64_dwarf_eval_expr: push -> 0x8
               >_ULx86_64_dwarf_eval_expr: OP_mul
               >_ULx86_64_dwarf_eval_expr: pop -> 0x8
               >_ULx86_64_dwarf_eval_expr: pop -> 0x7ffdbe4e7590
               >_ULx86_64_dwarf_eval_expr: push -> 0x3ffedf273ac80
               >_ULx86_64_dwarf_eval_expr: OP_plus
               >_ULx86_64_dwarf_eval_expr: pop -> 0x3ffedf273ac80
               >_ULx86_64_dwarf_eval_expr: pop -> 0x7ffdbe4e8c08
               >_ULx86_64_dwarf_eval_expr: push -> 0x47febb0c23888
               >_ULx86_64_dwarf_eval_expr: OP_deref
               >_ULx86_64_dwarf_eval_expr: pop -> 0x47febb0c23888
Segmentation fault (core dumped)
```
However, for the frame associated with this, the registers are different:
```
(gdb) bt
#0  dwarf_readu64 (as=<optimized out>, a=<optimized out>, arg=<optimized out>, val=<synthetic pointer>, addr=0x7ffdbe4e7128) at ../include/dwarf_i.h:128
#1  dwarf_readw (as=<optimized out>, a=<optimized out>, arg=<optimized out>, val=<synthetic pointer>, addr=0x7ffdbe4e7128) at ../include/dwarf_i.h:280
#2  _ULx86_64_dwarf_eval_expr (c=c@entry=0x7ffdbe4e7cd0, stack_val=stack_val@entry=0, addr=addr@entry=0x7ffdbe4e73d0, len=<optimized out>, valp=valp@entry=0x7ffdbe4e73d8,
    is_register=is_register@entry=0x7ffdbe4e73bc) at dwarf/Gexpr.c:435
#3  0x000055bfd20d72b5 in eval_location_expr (as=<optimized out>, a=<optimized out>, locp=<synthetic pointer>, locp=<synthetic pointer>, arg=<optimized out>, addr=<optimized out>, stack_val=0,
    c=0x7ffdbe4e7cd0) at dwarf/Gparser.c:756
#4  apply_reg_state (c=c@entry=0x7ffdbe4e7cd0, rs=rs@entry=0x7ffdbe4e76a8) at dwarf/Gparser.c:817
#5  0x000055bfd20d9c82 in _ULx86_64_dwarf_step (c=c@entry=0x7ffdbe4e7cd0) at dwarf/Gparser.c:974
#6  0x000055bfd20d4f42 in _ULx86_64_step (cursor=cursor@entry=0x7ffdbe4e7cd0) at x86_64/Gstep.c:75
#7  0x000055bfd20d6957 in trace_init_addr (rsp=140727796272128, rbp=0, rip=<optimized out>, cfa=140727796272128, cursor=0x7ffdbe4e7cd0, f=0x7f7081fa16d0) at ../include/tdep-x86_64/libunwind_i.h:218
#8  trace_lookup (rsp=140727796272128, rbp=0, rip=<optimized out>, cfa=140727796272128, cache=0x7f7082009fe0, cursor=0x7ffdbe4e7cd0) at x86_64/Gtrace.c:331
#9  _ULx86_64_tdep_trace (cursor=cursor@entry=0x7ffdbe4e7cd0, buffer=buffer@entry=0x55bfd22eb260 <frames>, size=size@entry=0x7ffdbe4e7914) at x86_64/Gtrace.c:449
#10 0x000055bfd20d4632 in unw_backtrace (buffer=0x55bfd22eb260 <frames>, size=64) at mi/backtrace.c:69
#11 0x000055bfd20cf2c3 in monitor () at test_bt.cpp:98
#12 <signal handler called>
#13 bn_mul_mont () at crypto/bn/x86_64-mont.s:163
#14 0x000055bfd20cefa6 in f3 (n1=38 '&', n2=58407, n3=480896040, n4=41 ')', n5=480896042, n6=43 '+', n7=480896044, n8=58413, n9=480896046) at test_bt.cpp:46
#15 0x000055bfd20cf188 in f2 (num=2, limit=2, n1=37 '%', n2=58406, n3=480896039, n4=40 '(', n5=480896041, n6=42 '*', n7=480896043, n8=58412, n9=480896045) at test_bt.cpp:73
#16 0x000055bfd20cf124 in f2 (num=1, limit=2, n1=36 '$', n2=58405, n3=480896038, n4=39 '\'', n5=480896040, n6=41 ')', n7=480896042, n8=58411, n9=480896044) at test_bt.cpp:67
#17 0x000055bfd20cf124 in f2 (num=0, limit=2, n1=35 '#', n2=58404, n3=480896037, n4=38 '&', n5=480896039, n6=40 '(', n7=480896041, n8=58410, n9=480896043) at test_bt.cpp:67
#18 0x000055bfd20cf266 in f1 (n=655417) at test_bt.cpp:82
#19 0x000055bfd20cf501 in main () at test_bt.cpp:136
(gdb) frame 13
#13 bn_mul_mont () at crypto/bn/x86_64-mont.s:163
(gdb) info reg
rax            0x0                 0
rbx            0x0                 0
rcx            0x7ffdbe4e8cc8      140727796272328
rdx            0x0                 0
rsi            0x55bfddd16c00      94282548603904
rdi            0x7ffdbe4e8cc0      140727796272320
rbp            0x0                 0x0
rsp            0x7ffdbe4e8c00      0x7ffdbe4e8c00
r8             0x0                 0
r9             0x4                 4
r10            0x0                 0
r11            0x0                 0
r12            0x55bfddd16d10      94282548604176
r13            0x0                 0
r14            0x1                 1
r15            0x2                 2
rip            0x55bfd20cfb10      0x55bfd20cfb10 <bn_mul_mont+400>
eflags         0x10206             [ PF IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
(gdb)
```
Note that `r9` has the value of `0x4` in gdb, but libunwind thinks it's `0x7ffdbe4e7590`, and using that value completely messes up the calculation that leads to `deref`.

See https://github.com/tmshort/backtrace for the above buildable/crashable example. Building this (with OpenSSL_1_1_1-stable and libunwind master), and running will eventually crash.

**Comment by tmshort** [comment]
Based on `gdb` being able to unwind the stack, and libunwind being able to parse/decode the CFI/CFA expression (so OpenSSL appeared to have constructed it correctly), leads me to think that this is a bug in libunwind.

**Comment by djwatson** [comment]
Wow, thanks for the extensive bug report, this definitely helps a lot!

I haven't yet run your test example, but based on your description of r9 being the wrong value, and using unw_backtrace, I'm suspecting that it's because unw_backtrace uses getcontext_trace, which doesn't capture r9, instead of getcontext which captures everything.

a) You can try changing 'tdep_getcontext_trace' in unw_backtrace to 'unw_getcontext' instead.  

b) Or in your user code do a normal unw_getcontext, unw_init_local, unw_step, unw_get_reg(... UNW_REG_IP) loop (as in slow_backtrace).

**Comment by djwatson** [comment]
and verified that a) fixes your test case. 

I'll have to think about how to really fix it though, tdep_trace needs to fail if we access more than the four trace registers we save (rbp, rbx, rsp, rip)

**Comment by tmshort** [comment]
Yes, I just tried it too, and it's working better. I want to make sure I get a trace inside of bn_mul_mont, however. :)

**Comment by tmshort** [comment]
I'm hitting bn_mul_mont()... but I'm also running out of memory. It's a weird memory leak. But I'm able to get around that, and the program is detecting that it's hitting inside of `bn_mul_mont()`

**Comment by djwatson** [comment]
I made an attempt at a 'real' fix, give it a try when you get a chance:

https://github.com/libunwind/libunwind/pull/265

I'm also seeing a memory leak, but haven't found teh root cause yet.

**Comment by tmshort** [comment]
> Edit: leak appears even without unw_backtrace, so it's probably not libunwind.

Yup, it's in test_bt.

**Comment by tmshort** [comment]
I updated my repo so that test_bt.cpp no longer sucks up all memory, and to use a patched version of libunwind
