### ISSUE TITLE
Cross compilation is actually broken

### ISSUE THREAD

**Issue by kasperk81** [libunwind/libunwind#268]
If we look at the CI logs, e.g. s390x https://travis-ci.com/github/libunwind/libunwind/jobs/519138896, we see:

> checking whether we are cross compiling... no

so we end up compiling everything with host (x86_64) compiler.
the reason for that is; HOST is not set in default environment (stare at .travis.yml for a while; it's a tricky one).

But what really happens when we set HOST and TARGET correctly is we get

> checking if libtool supports shared libraries... **no**
> checking whether to build shared libraries... **no**

and as a result, we only get src/.libs/libunwind.a archive rather than an SO file.

Compelete examples:

1. cross compile arm-linux-gnueabihf on Ubuntu x64:

```sh
docker run -it ubuntu:latest

apt update
apt install -y git automake make libtool-bin g++-arm-linux-gnueabihf

git clone https://github.com/libunwind/libunwind
cd libunwind
autoreconf -i

./configure --enable-shared \
    CC=arm-linux-gnueabihf-gcc \
    CXX=arm-linux-gnueabihf-g++ \
    AR=arm-linux-gnueabihf-ar \
    RANLIB=arm-linux-gnueabihf-ranlib \
    STRIP=arm-linux-gnueabihf-strip \
    --target=arm-unknown-linux-gnueabihf \
    --host=x86_64-linux-gnu > fulllog 2>&1

# check ./fulllog which says:

# checking whether the arm-linux-gnueabihf-gcc linker (/usr/arm-linux-gnueabihf/bin/ld -m elf_i386) supports shared libraries... /usr/arm-linux-gnueabihf/bin/ld: unrecognised emulation mode: elf_i386
# Supported emulations: armelf_linux_eabi armelfb_linux_eabi
# no
# checking dynamic linker characteristics... GNU/Linux ld.so
# checking how to hardcode library paths into programs... unsupported
# checking whether stripping libraries is possible... yes
# checking if libtool supports shared libraries... no
# checking whether to build shared libraries... no
# checking whether to build static libraries... yes


# we expect all shared libraries lines to be "yes"
```

2. cross compile IA64 on gentoo x64

```sh
docker run -it gentoo/stage3
# setup and update packages repository
emerge-webrsync
emerge sys-devel/crossdev app-eselect/eselect-repository dev-vcs/git
mkdir -p /etc/portage/repos.conf/
eselect repository create localrepo

# emerge ia64 cross compiler
crossdev -t ia64-unknown-linux-gnu --with-headers

# build libunwind
git clone https://github.com/libunwind/libunwind
cd libunwind
autoreconf -i
./configure --enable-shared \
    CC=/usr/x86_64-pc-linux-gnu/ia64-unknown-linux-gnu/gcc-bin/11.1.0/ia64-unknown-linux-gnu-gcc \
    CXX=/usr/x86_64-pc-linux-gnu/ia64-unknown-linux-gnu/gcc-bin/11.1.0/ia64-unknown-linux-gnu-g++ \
    --host=x86_64-pc-linux-gnu \
    --target=ia64-unknown-linux-gnu > fulllog 2>&1

# now check the "fulllog" file, same situation that shared libraries lines are "no" instead of "yes"
```

**Comment by kasperk81** [comment]
cc @trofi, @Arfrever @xcoldhandsx if you guys have any idea what is missing from autoconf setup in this repo?

**Comment by trofi** [comment]
You probably want `./configure --build=x86_64-pc-linux-gnu --host=ia64-unknown-linux-gnu`

**Comment by kasperk81** [comment]
build is evaluated correctly:

> checking build system type... x86_64-pc-linux-gnu

but setting it explicity also didn't fix the "supports shared libraries" issue (still "no" instead of "yes").

**Comment by trofi** [comment]
You'll need to check `config.log` for specifics. The chances are some `libunwind` depend is not yet installed for that target.

**Comment by kasperk81** [comment]
config.log apparently omits the stderr, which is why i redirected all output to a file called `fulllog`. but config.log has other information.

From gentoo example above "ia64 cross compile on x64":

example2's config.log: http://sprunge.us/HaTbrb
example2's fulllog: http://sprunge.us/29M1WZ

do you see anything particular missing which could cause "support shared libraries" lines evaluating to "no"?

**Comment by trofi** [comment]
> configure:10094: checking whether the /usr/x86_64-pc-linux-gnu/ia64-unknown-linux-gnu/gcc-bin/11.1.0/ia64-unknown-linux-gnu-gcc linker (/usr/libexec/gcc/ia64-unknown-linux-gnu/ld -m elf_x86_64) supports shared libraries

ia64 ld does not support x86_64 ELF ABI.

>   $ ./configure --enable-shared CC=/usr/x86_64-pc-linux-gnu/ia64-unknown-linux-gnu/gcc-bin/11.1.0/ia64-unknown-linux-gnu-gcc CXX=/usr/x86_64-pc-linux-gnu/ia64-unknown-linux-gnu/gcc-bin/11.1.0/ia64-unknown-linux-gnu-g++ --host=x86_64-pc-linux-gnu --target=ia64-unknown-linux-gnu

You probably want `--build=x86_64-pc-linux-gnu --host=ia64-unknown-linux-gnu`. https://www.gnu.org/software/autoconf/manual/autoconf-2.65/html_node/Specifying-Target-Triplets.html has more words what `--build`/`--host` mean. Tl;DR is:
1. if it's not a compiler you built you probably never want `--target=`. `libunwind` is not a cross-compliler and just a library.
2. `--build` is where you plan to compile the project (I assume it's x86_64-pc-linux-gnu for you)
3. `--host` is where the compiled result is expected to be ran (I assume it's ia64-unknown-linux-gnu for you)

**Comment by kasperk81** [comment]
Thanks! it indeed was a mistake. Both gentoo and ubuntu examples above are working:

Example 1 fix
```diff
-    --target=arm-unknown-linux-gnueabihf \
-    --host=x86_64-linux-gnu > fulllog 2>&1
+    --build=x86_64-linux-gnu \
+    --host=arm-unknown-linux-gnueabihf > fulllog 2>&1
```
Example 2 fix
```diff
-    --host=x86_64-pc-linux-gnu \
-    --target=ia64-unknown-linux-gnu > fulllog 2>&1
+    --build=x86_64-pc-linux-gnu \
+    --host=ia64-unknown-linux-gnu > fulllog 2>&1
```

Still, it means CI is wrong, yest? https://github.com/libunwind/libunwind/blob/ffd0c05e8fabef6e2f41569c8d5680eaf5168749/.travis.yml#L33
