### ISSUE TITLE
Build failing while cross compiling for "arm-linux-android"

### ISSUE THREAD

**Issue by brainbreaker** [libunwind/libunwind#27]
I want to cross compile for host "arm-linux-android" on my linux_x86-64 machine. 
As per instructions in "INSTALL" file generated after running autogen.sh and config.sub, I did
`./configure --host="arm-linux-android"`

Configure ran successfully but when I did 'make', build failed with these errors: https://pastebin.ca/3833752

Looking at the errors, it can't seem to find the declared variables for ARM registers like UNW_ARM_S0, UNW_ARM_F0 etc. They are declared in libunwind-arm.h header. 

The file throwing the error "arm/is_fpreg.c" does not import "libunwind-arm.h", so I tried to add this header in the include but it didn't work out. 

I looked at the Makefile generated after configure, I could not find any abnormalities regarding build or host platform. It appears to detect correct files and system types. 
Here's the part which I think can be relevant. 

> build_triplet = x86_64-pc-linux-gnu
> host_triplet = arm-unknown-linux-android
> target_triplet = arm-unknown-linux-android
> am__append_1 = include/libunwind-ptrace.h
> am__append_2 = include/libunwind-coredump.h
> #am__append_3 = include/libunwind-aarch64.h
> am__append_4 = include/libunwind-arm.h
> #am__append_5 = include/libunwind-ia64.h
> #am__append_6 = include/libunwind-hppa.h
> #am__append_7 = include/libunwind-mips.h
> #am__append_8 = include/libunwind-tilegx.h
> #am__append_9 = include/libunwind-x86.h
> #am__append_10 = include/libunwind-x86_64.h
> #am__append_11 = include/libunwind-ppc32.h
> #am__append_12 = include/libunwind-ppc64.h
> #am__append_13 = include/libunwind-sh.h
> am__append_14 = include/libunwind.h include/unwind.h
> am__append_15 = tests
> #am__append_16 = doc

Let me know if more information is required or if I missed something while building. I'd be happy to fix this. 
I'm able to successfully build with default values i.e ./configure without any parameters. It correctly detects my build and host triplet as "x86_64-pc-linux-gnu".

**Comment by djwatson** [comment]
I'm fairly certain you need to also specify the correct cross compiler.  We build arm-linux-gnueabihf on travis, and it seems to work
