### ISSUE TITLE
Blocked Builds on Travis 

### ISSUE THREAD

**Issue by anujajakhade** [libunwind/libunwind#281]
It is observed that the builds for libunwind are blocked on [Travis ](https://travis-ci.com/github/libunwind/libunwind)due to negative credit balance.
As per the Travis [blog](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), Travis fully supports the OSS teams and allocate them more credits after they apply for same. 
Could you please open a request with Travis CI support stating that you'd like to be considered for the OSS allotment?
Please refer the Travis [blog ](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)for more details on how to open support request with Travis.

**Comment by djwatson** [comment]
I have opened a support request requesting OSS credits.  Thanks for the links & heads up.

**Comment by djwatson** [comment]
travis as gifted us 25k credits.

**Comment by kasperk81** [comment]
@djwatson, i think we should move to github actions as @zhaofengli is suggesting. TravisCI is not free anymore and people in fork cannot use those gifted credits. GitHub Actions is free and can be used in forks.

**Comment by djwatson** [comment]
@kasperk81 I'm in favor of trying github actions.  I probably won't have time for a week or two to work on it though, feel free to send pull requests.

**Comment by anujajakhade** [comment]
@djwatson s390x / Z architecture doesn't have native build support on GA. If CI is to be shifted to GA, what can be done to keep Travis builds alive?

**Comment by djwatson** [comment]
We can do both

**Comment by kasperk81** [comment]
Switching to github actions doesn't mean we will not build for s390x, it only means we won't be running tests (as we are not running tests in travis-ci for more important architectures like aarch64...).
Cross-build will be supported in GitHub Actions for all architectures that we support on TravisCI.
