### ISSUE TITLE
unw_backtrace success, but unw_step fail

### ISSUE THREAD

**Issue by 616050468** [libunwind/libunwind#282]
hi, I recently encountered some problems with libunwind on ubuntu16.04, unw_step will fail sometimes, but unw_backtrace can be successful.  something like this below:

unw_backtrace frame_count: 45
ip:0x41e358
ip:0x41e7bb
ip:0x41ff1f
....

unw_step frame_count: 3
ip:0x41e358
ip:0x66fd162363d0bc4b
ip:0x7fc83fdf68c0

code:
static int sample(void* ucontext) {
    unw_cursor_t cursor;
    unw_word_t ip, bx;
    unw_context_t uc;
    if (unw_init_local (&cursor, ucontext) < 0)
    {
        printf("[trace_inject] unw_init_local failed!\n");
        return 0;
    }
    do {
         unw_get_reg(&cursor, UNW_REG_IP, &ip);
         unw_get_reg(&cursor, UNW_X86_64_RBX, &bx);
    } while (unw_step(&cursor) > 0);
}
by the way, I use libunwind to get backtrace in a signal.  how can i know what's wrong??

**Comment by 616050468** [comment]
maybe I know what's wrong.  I should not pass the uconext  of signal handler to unw_init_local.  I should use unw_getcontext.  Am I right?

**Comment by patrickdepinguin** [comment]
You may be interested in following example:
https://github.com/cslarsen/libunwind-examples/blob/master/backtrace.cpp
