### ISSUE TITLE
--enable-shared --disable-static installs broken symlink

### ISSUE THREAD

**Issue by MarcoKoch** [libunwind/libunwind#29]
I recently packaged libunwind for the conan package manager. In the course of that I noticed a small bug in libunwind's build system:

If I configure with `./configure --prefix= --enable-shared --disable-static`, a broken symlink `lib/libunwind-generic.a` is installed that points to a missing architecture-specific version of that library (e.g. `lib/libunwind-x86_64.a`). I suppose that not installing that library is the intended behavior with these configuration settings, so the symlink should not be there in the first place.

I was able to reproduce this bug on several Linux systems, native on x86_64 as well as cross-compiling to i686. I tried both, libunwind versions 1.2 and 1.2.1 from <http://download.savannah.nongnu.org/releases/libunwind/> as well as the current version here on GitHub (commit 2934cf40529e0261801a4142fabae449a65effd0). For the latter I used libtool version 2.4.6 from the Fedora 25 package repository. All tests showed the same behavior.

**Comment by djwatson** [comment]
Fixed in 4e8b7a595e144e905fd9c8aed053d7529afb78a4

Thanks
