### ISSUE TITLE
cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by 616050468** [libunwind/libunwind#292]
I use libunwind.so in other so, but error happen like this:
/usr/local/lib/libunwind.so.8: cannot allocate memory in static TLS block

it run ok, if use tls_mode("local-dynamic")

  if (likely (caching == UNW_CACHE_PER_THREAD))
    {
      static __thread struct dwarf_rs_cache tls_cache __attribute__((tls_model("initial-exec")));
      Debug (16, "using TLS cache\n");
      cache = &tls_cache;
    }

**Comment by djwatson** [comment]
You probably have to link libunwind statically if you want initial-exec?

**Comment by 616050468** [comment]
I get new problem:
/usr/bin/ld: /usr/local/lib/libunwind.a(Ltrace.o): relocation R_X86_64_TPOFF32 against `tls_ep_add efd:3 fd:4 ud:0x7f2720345018                                                            │cache_destroyed' can not be used when making a shared object; recompile with -fPIC

why libunwind build without -fPIC??

**Comment by 616050468** [comment]
LDFLAGS="-lpthread -ldl -lm -l:libunwind.a -l:libunwind-ptrace.a -l:libunwind-x86_64.a"

I build my so with LDFLAGS="-lpthread -ldl -lm -l:libunwind.a -l:libunwind-ptrace.a -l:libunwind-x86_64.a"， but cannot solve the problem

**Comment by bregma** [comment]
If you're trying to embed libunwind statically in another DSO you'll need to add the -fPIC to the CFLAGS yourself when you build it from source.
