### ISSUE TITLE
libunwind 1.2.1 UNW_VERSION_MINOR is not an integer

### ISSUE THREAD

**Issue by orivej** [libunwind/libunwind#30]
Configuring libunwind 1.2.1 after `autoreconf` generates this in `include/libunwind-common.h`:
```
#define UNW_VERSION_MAJOR	1
#define UNW_VERSION_MINOR	2.1
#define UNW_VERSION_EXTRA	
```
Since UNW_VERSION_MINOR is not an integer, it is not comparable in macros.

This happens because `configure.ac` contains
```
define(pkg_major, 1)
define(pkg_minor, 2.1)
define(pkg_extra, )
```

This breaks compilation of julia 0.5.1:
```
src/julia_internal.h:496:35: error: floating constant in preprocessor expression
        (UNW_VERSION_MAJOR == 1 && UNW_VERSION_MINOR > 1))
                                   ^
```

Discovered in https://github.com/NixOS/nixpkgs/pull/26891#issuecomment-312704756

**Comment by djwatson** [comment]
Sure can change UNW_VERSION_EXTRA to contain the 1 instead

**Comment by orivej** [comment]
Looking at `mkvers`
```
define(mkvers, $1.$2$3)
dnl Process this file with autoconf to produce a configure script.
AC_INIT([libunwind],[mkvers(pkg_major, pkg_minor, pkg_extra)],[pkg_maintainer])
```
it might be better to set `pkg_extra` to `.1` so that concatenated version becomes `1.2.1`. (Maybe `.1` might be omitted at all, as it was in `1.0.1`?)
Nethertheless `1.2.1` is already tagged, so I hope for this issue not to reoccur in `1.2.2` and future releases.

**Comment by djwatson** [comment]
Sure, thanks, will make sure this is correct for the next release.

**Comment by orivej** [comment]
Thank you!
