### ISSUE TITLE
Question on JIT Compiling

### ISSUE THREAD

**Issue by ruggedmongoose** [libunwind/libunwind#302]
Hello, I'm with www.flexsim.com, and I'm trying to port our application from windows to linux amd64 architecture. The application includes JIT-compiled code, and I'm trying to figure out how to get exception handling to work.

The main application is in C++, compiled with clang. JIT vs. C++ code execution is very fluid, as C++ will call JIT code and vice versa. The JIT code does not contain try-catch constructs, but I want clang's exception unwinder to be able to unwind the stack (and give me callbacks so I can clean up objects) through any JIT code until it finds a C++ catch handler.

I was hoping to be able to use _U_dyn_register() for this, but have not been successful yet. Looking at the source code, it appears that this function only populates a self-managed linked list. It doesn't register this information with any unwinding substructure, which I assume is what would be needed for the clang unwinder to integrate it properly. So I'm kind of at a loss as to whether libunwind is what I'm looking for. I've looked into calling clang/gcc's __register_frame_info(), but haven't wrapped my head all the way around that yet. Any advice would be greatly appreciated.

**Comment by yuyichao** [comment]
This isn't a libunwind issue. You need to register it with the system unwinder (libgcc) and the function to use is `__register_frame`.

**Comment by ruggedmongoose** [comment]
Yes, I know it's not an issue, but the [latest post on libunwind](https://savannah.nongnu.org/news/?group=libunwind) says the mailing lists aren't being used and that I should post here.

Anyway, thank you for that clarification. I'll dig into calling __register_frame.

**Comment by djwatson** [comment]
I vaguely recall that the dyn_info stuff was only ever implemented for ia64 - as mentioned, most people don't use libunwind for actual exception unwinding anymore and use gcc's unwinder.

**Comment by yuyichao** [comment]
> This isn't a libunwind issue

I actually meant that you might have better luck finding more detail from gcc/libgcc instead.
Calling `__register_frame` with the `.eh_frame` address is about as much I knew (and needed) about that = = .....
