### ISSUE TITLE
Is support to GCC < 4.9 dropped ?

### ISSUE THREAD

**Issue by Boucher-Lambert** [libunwind/libunwind#304]
Hi,

https://github.com/libunwind/libunwind/commit/45fc222a00f239a16f1420c4446113e8a730b75a shows that new 1.6 version of libunwind heavily relies on C11.

C11 is fully supported in GCC starting from 4.9 version.

stdatomic.h is not provided in the GCC 4.8 https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58016

Hence libunwind is not compiled with GCC 4.8

10:18:09 libtool: compile:  arm-openwrt-linux-uclibcgnueabi-gcc -DHAVE_CONFIG_H -I. -I../include -I../include -I../include/tdep-arm -I. -I/home/ipkg/openwrt/staging_dir/target-arm_cortex-a7_uClibc-0.9.33.2_eabi/usr/include -I/home/ipkg/openwrt/staging_dir/target-arm_cortex-a7_uClibc-0.9.33.2_eabi/include -I/home/ipkg/openwrt/staging_dir/toolchain-arm_cortex-a7_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/usr/include -I/home/ipkg/openwrt/staging_dir/toolchain-arm_cortex-a7_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/include -D_GNU_SOURCE -DNDEBUG -std=c99 -Os -pipe -march=armv7-a -mtune=cortex-a7 -fno-caller-saves -fstack-protector -Wl,-z,relro,-z,now -fhonour-copts -Wno-error=unused-but-set-variable -mfloat-abi=soft -DIP_TRANSPARENT=19 -DIP_FREEBIND=15 -UGIT_VERSION -ggdb3 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -MT os-linux.lo -MD -MP -MF .deps/os-linux.Tpo -c os-linux.c  -fPIC -DPIC -o .libs/os-linux.o
10:18:09 In file included from ../include/tdep/libunwind_i.h:9:0,
10:18:09                  from ../include/libunwind_i.h:347,
10:18:09                  from os-linux.c:30:
10:18:09 ../include/tdep-arm/libunwind_i.h:33:23: fatal error: stdatomic.h: No such file or directory
10:18:09  #include <stdatomic.h>
10:18:09                        ^
10:18:09 compilation terminated.

Was it intentional to drop support to GCC < 4.9 ?

Thanks, Timothee

**Comment by kasperk81** [comment]
Yes gcc 4.9.0 is required at minimum which has complete C11 support. Also note that in 4.9 series, libunwind needs explicit std=c11 cflags:

```
autoreconf -i
./configure CFLAGS="-std=c11"
make
make check
```
starting with 5.1.0, `CFLAGS="-std=c11"` is not needed.

**Comment by Boucher-Lambert** [comment]
Thank you for your answer. Closing the issue.
