### ISSUE TITLE
make check fail

### ISSUE THREAD

**Issue by philGemini** [libunwind/libunwind#306]
system : wsl2 ubuntu 20.04
action:
autoreconf -i  
sudo make 
make check 
got one fail 
FAIL: run-coredump-unwind 

I wonder is it a critical issure.

tests/test-suite.log
libunwind 1.6-rc1: tests/test-suite.log
=============================================

# TOTAL: 37
# PASS:  36
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: run-coredump-unwind
=========================

Segmentation fault (core dumped)
FAILURE: start IPs incorrect
FAIL run-coredump-unwind (exit status: 255)

**Comment by shonaweldon** [comment]
I got the same test failing with the same steps except: 
system: CentOS Linux release 8.4.2105
libunwind version: v1.5

and the details for the run-cordump-unwind are:

```
FAIL: run-coredump-unwind
=========================

lt-test-coredump-unwind: _UCD_create('/tmp/libunwind-test-4QZkFtPsLq/core*') failed
FAIL run-coredump-unwind (exit status: 1)
```

**Comment by djwatson** [comment]
This is generally caused because you have a non-empty core_pattern (cat /proc/sys/kernel/core_pattern), so the core file doesn't end up in the current directory.
