### ISSUE TITLE
Re-tag 1.5.0 as v1.5.0 instead of v1.5

### ISSUE THREAD

**Issue by ararslan** [libunwind/libunwind#309]
Version 1.5.0 was tagged as v1.5 rather than v1.5.0, which makes handling libunwind installations that use git tags a bit more annoying (see e.g. https://github.com/JuliaLang/julia/pull/42782/files#diff-3337b801a52c5fc1a204a84513c7d320a6623f331836a83aadaca8250db623f6R7). If you'd be willing to add a v1.5.0 tag based on 4c980e2b29cdb9d21cfc341abdec3a6ee46e0483, that would be awesome!

**Comment by djwatson** [comment]
I added an additional tag v1.5.0 the same as v1.5.  Let me know if you want something else.

**Comment by ararslan** [comment]
That's perfect, thanks!
