### ISSUE TITLE
Question: is it possible to get source code file and line number?

### ISSUE THREAD

**Issue by f18m** [libunwind/libunwind#310]
Hi,
sorry but I couldn't find the answer looking at https://www.nongnu.org/libunwind/docs.html.
I would like to get a backtrace in case of failure of my C++ software containing the source code file name and the line number for each frame of the stack.
I found this code:
  https://gist.github.com/fmela/591333/c64f4eb86037bb237862a8283df70cdfc25f01d3
which uses a combination of backtrace()+backtrace_symbols()+dladdr()+abi::__cxa_demangle() to almost fit my need. Only issue with such solution for me is that it's missing the line number.

Is it possible to get the line number into the source code associated with the function of the backtrace using libunwind?

Thanks!!

**Comment by milianw** [comment]
It sounds like you should look into https://github.com/bombela/backward-cpp which makes this task pretty easy. Otherwise if you are set on rolling your own solution, I suggest you look into elfutils' libdwfl for the symbolication. Alternatively there is also libbacktrace.

Cheers

**Comment by f18m** [comment]
Thanks a lot for the pointers! Backward-cpp is what I was looking for!!
