### ISSUE TITLE
Will recent bugfixes on master get backported into the 1.6 branch?

### ISSUE THREAD

**Issue by acmorrow** [libunwind/libunwind#321]
I'm in the process of evaluating an upgrade from libunwind 1.5 to 1.6, primarily in the interest of improved ARM support. I noticed that shortly after the 1.6 branch was pulled, there were several bug fixes that landed on master that looked like they might be fairly important:

- https://github.com/libunwind/libunwind/commit/971989687f9cf46d9d7f95df593657e455d96493
- https://github.com/libunwind/libunwind/commit/400b3f819ad44ff4e15487b163cc3613389cb4c8
- https://github.com/libunwind/libunwind/commit/4d779f55c0d0a3814453517e54cd0f7bed69ca74
- https://github.com/libunwind/libunwind/commit/8b3832fea8a343ec0888545088c859074aaee20f

As I'm not particularly familiar with libunwind's development processes, I was curious whether bugfixes like these tended to get backported to stable branches like 1.6 and so show up in a future 1.6.3, or whether these are likely to appear only in a future 1.7.0 release. If these fixes are unlikely to be backported to 1.6 in the official libunwind releases, would it be reasonable/advisable for us to cherry-pick them into our own 1.6-based tree?

Finally, If I'm mistaken about the importance of these fixes, that'd be good to know as well.

**Comment by djwatson** [comment]
The first three are large enough I'd prefer waiting until 1.7.  I can backport the last, it's pretty straightforward.

Feel free to cherry pick them to your own tree - although I think only 4d779f5 will affect arm (and it's definitely a logic change that will wait until 1.7).
