### ISSUE TITLE
test looped infinitely in aarch64 

### ISSUE THREAD

**Issue by pyqhaoku** [libunwind/libunwind#323]
[root@simon28li spack-src]# spack debug report
* **Spack:** 0.16.1
* **Python:** 3.6.8
* **Platform:** linux-centos8-aarch64
* **Concretizer:** original

when i do 'make check' in the machine, test program looped infinitely in function 'stepper' of tests/Ltest-init-local-signal.c. 
This error occurs in  versions 1.6.0-1.6.2

**Comment by bregma** [comment]
In our latest CI runs (Ubuntu 20.02 LTS, GCC=aarch64-unknown-linux-gnu 9.3.0) [this test passes](https://app.travis-ci.com/github/libunwind/libunwind/jobs/576836368) on mainline.

Could you please rerun your test using the current mainline and report the results back here? This issue may have been fixed by the intervening changes targeting aarch64.

**Comment by Boucher-Lambert** [comment]
Hi,

I am encountering a very similar issue.

The environment:
`$ uname -a
Linux xxx.xxx.xxx.net 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/issue
Ubuntu 20.04.4 LTS \n \l
`

Testing the v1.6.2
It seems the "--disable-ptrace" is needed to trigger more easily the hanging.
Several run may be needed.

`$ git fetch "https://git.savannah.gnu.org/git/libunwind.git/" v1.6.2 && git checkout FETCH_HEAD
$ autoreconf -i ; ./configure --disable-ptrace ; make ; make check`

I got

PASS: test-proc-info
PASS: test-static-link
PASS: test-strerror
PASS: Gtest-bt
PASS: Ltest-bt
PASS: Gtest-exc
PASS: Ltest-exc
PASS: Gtest-init
PASS: Ltest-init
PASS: Ltest-concurrent
PASS: Gtest-resume-sig
PASS: Ltest-resume-sig
PASS: Gtest-resume-sig-rt
PASS: Ltest-resume-sig-rt
PASS: Gtest-trace
PASS: Ltest-trace
PASS: Ltest-init-local-signal
PASS: Ltest-mem-validate

Then the test hangs forever in  test-async-sig. 
When commenting line 113 of tests/test-async-sig.c file (call to unw_step), the test fails but does not hang.

I never reproduced it on master or v1.4 branches, only on v1.6.

I have an environment test ready that can reproduce the problem hence I can try more things if somebody has ideas.

**Comment by Boucher-Lambert** [comment]
I did the bisection in between v1.6.2 and master and found the commit fixing the hanging.

b06ef3d1 Fix to malloc call in tdep_get_elf_image

This commit can be backported without conflict on v1.6.2 and it solves the issue, which appear to be not linked to aarch64 in the end.

**Comment by pyqhaoku** [comment]
thanks.
In master, the problem is solved.
After testing, I found that the problem was solved in e85b65cec757ef589f28957d0c6c21c498a03bdf. It may be caused by pagesize.
