### ISSUE TITLE
How to build libunwind for QNX?

### ISSUE THREAD

**Issue by alaahl** [libunwind/libunwind#326]
Hi,

I am unable to build libunwind for QNX (x86_64).
I am running ./configure --host=x86_64-pc-nto-qnx7.1.0
Then make fails with this error:

```
_x86_64/setcontext.S:58:2: error: #error Port me
 #error Port me
  ^~~~~
Makefile:4320: recipe for target 'x86_64/setcontext.lo' failed
make[2]: *** [x86_64/setcontext.lo] Error 1

```

I tried resetting the branch to commit eac65dc9b8cc ("Add basic support for the QNX operating system"), however it still failed with the same error... how did that commit compile?

I also tried with setting CC="qcc -Vgcc_ntox86_64" .

I'm probably missing something...
Any help would be much appreciated.

Thanks,
Alaa

**Comment by aamartir** [comment]
Hi @alaahl, did you figure out what was the correct ./configure parameter/s to build for QNX (aarch64)? I'm having similar issues on my end.

**Comment by bregma** [comment]
The port to QNX is incomplete: no amount of configure parameters will result in a working library.

A fix is in the pipes.
