### ISSUE TITLE
libunwind hardcodes PAGE_SIZE

### ISSUE THREAD

**Issue by dmoody256** [libunwind/libunwind#328]
In #212, I had started to take a look at libunwind on various arm platforms, and I found that libunwind was hardcoding a standard PAGE_SIZE, which was not working on one of my systems which had a different page size.

I found I could determine the page size dynamically at runtime using `sysconf(_SC_PAGESIZE)` via  [sysconf](https://man7.org/linux/man-pages/man3/sysconf.3.html), which was working across my various test platforms. 

I have a [small dev patch]( https://github.com/mongodb-forks/libunwind/commit/8e357e280cf5b2bd76520c5b8a96b8d8599986f8) I was using, but I would like the maintainer to take a look and fix this issue as they see fit. Since the arm code was ported from x86, I think this affects several other platforms.

**Comment by tpwrules** [comment]
Does this have a significant effect on runtime performance? Have you been able to run the tests? I have an AArch64 system with 16K pages and this causes problems for me too.

**Comment by dmoody256** [comment]
@tpwrules I have not analyzed the performance precisely yet, but it seems to not make a noticeable difference in my tests. Not that the sysconf call only happens in the init, at the same time it is determined if mincore is available.
