### ISSUE TITLE
build failed for aarch64, undefined reference to `_ULaarch64_init_local'

### ISSUE THREAD

**Issue by getnextwindow1** [libunwind/libunwind#337]
i need to build libunwind (1.5 version release)on ubuntu x86_64 for aarch64 with aarch64 toolchain, commands:

CC=aarch64-openwrt-linux-gcc CXX=aarch64-openwrt-linux-g++ LD=aarch64-openwrt-linux-ld AR=aarch64-openwrt-linux-ar AS=aarch64-openwrt-linux-as NM=aarch64-openwrt-linux-gcc-nm STRIP= RANLIB=aarch64-openwrt-linux-gnu-strip  OBJDUMP=aarch64-openwrt-linux-gnu-objdump ./configure --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=aarch64-openwrt-linux-gnu

error mesage:
../libtool: link: aarch64-openwrt-linux-gcc -march=armv8-a -DARCH_AARCH64 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -o .libs/Gperf-simple Gperf-simple.o  ../src/.libs/libunwind-aarch64.so ../src/.libs/libunwind.so
aarch64-openwrt-linux-gnu-gcc.bin: warning: environment variable 'STAGING_DIR' not defined
aarch64-openwrt-linux-gnu-gcc.bin: warning: environment variable 'STAGING_DIR' not defined
../src/.libs/libunwind.so: undefined reference to `_ULaarch64_dwarf_find_proc_info'
../src/.libs/libunwind.so: undefined reference to `_ULaarch64_dwarf_make_proc_info'
../src/.libs/libunwind-aarch64.so: undefined reference to `_Uaarch64_dwarf_flush_rs_cache'
../src/.libs/libunwind.so: undefined reference to `_ULaarch64_dwarf_apply_reg_state'
../src/.libs/libunwind.so: undefined reference to `_ULaarch64_dwarf_put_unwind_info'
../src/.libs/libunwind-aarch64.so: undefined reference to `_Uaarch64_dwarf_search_unwind_table'
../src/.libs/libunwind-aarch64.so: undefined reference to `_Uaarch64_dwarf_make_proc_info'
../src/.libs/libunwind-aarch64.so: undefined reference to `_Uaarch64_dwarf_apply_reg_state'
../src/.libs/libunwind.so: undefined reference to `_ULaarch64_dwarf_reg_states_iterate'
../src/.libs/libunwind.so: undefined reference to `_ULaarch64_dwarf_step'
../src/.libs/libunwind.so: undefined reference to `_ULaarch64_dwarf_search_unwind_table'
../src/.libs/libunwind-aarch64.so: undefined reference to `_Uaarch64_dwarf_reg_states_iterate'
../src/.libs/libunwind-aarch64.so: undefined reference to `_Uaarch64_dwarf_init'
../src/.libs/libunwind-aarch64.so: undefined reference to `_Uelf64_get_proc_name'
;?

libunwind-aarch64.so or libunwindo.so does not have above symbols:
nm libunwind.so |grep dwarf
                 U _Uaarch64_dwarf_init
                 U _ULaarch64_dwarf_apply_reg_state
                 U _ULaarch64_dwarf_find_proc_info
                 U _ULaarch64_dwarf_flush_rs_cache
                 U _ULaarch64_dwarf_make_proc_info
                 U _ULaarch64_dwarf_put_unwind_info
                 U _ULaarch64_dwarf_reg_states_iterate
                 U _ULaarch64_dwarf_search_unwind_table
                 U _ULaarch64_dwarf_step

How can fix this problem?

**Comment by zcchm** [comment]
aarch64-openwrt-linux-gnu-gcc.bin: warning: environment variable 'STAGING_DIR' not defined

you should define STAGING_DIR env var.

**Comment by getnextwindow1** [comment]
> aarch64-openwrt-linux-gnu-gcc.bin: warning: environment variable 'STAGING_DIR' not defined
> 
> you should define STAGING_DIR env var before build.

-------------

Thanks for your apply. after setting STAGING_DIR env var，it still have errors:

libtool: link: (cd .libs/libunwind-dwarf-generic.lax/libunwind-dwarf-common.a && aarch64-openwrt-linux-ar x "/disk1/debai/Applications/libunwind/src/./.libs/libunwind-dwarf-common.a")
libtool: link: aarch64-openwrt-linux-ar cru .libs/libunwind-dwarf-generic.a dwarf/.libs/Gexpr.o dwarf/.libs/Gfde.o dwarf/.libs/Gparser.o dwarf/.libs/Gpe.o dwarf/.libs/Gfind_proc_info-lsb.o dwarf/.libs/Gfind_unwind_table.o   .libs/libunwind-dwarf-generic.lax/libunwind-dwarf-common.a/global.o 
aarch64-openwrt-linux-ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: aarch64-openwrt-linux-gnu-strip .libs/libunwind-dwarf-generic.a
libtool: link: rm -fr .libs/libunwind-dwarf-generic.lax
libtool: link: ( cd ".libs" && rm -f "libunwind-dwarf-generic.la" && ln -s "../libunwind-dwarf-generic.la" "libunwind-dwarf-generic.la" )
/bin/sh ../libtool  --tag=CC   --mode=link aarch64-openwrt-linux-gcc  -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -XCClinker -nostartfiles -version-info 8:1:0               -o libunwind-aarch64.la -rpath /usr/local/lib os-linux.lo dl-iterate-phdr.lo mi/init.lo mi/flush_cache.lo mi/mempool.lo mi/strerror.lo aarch64/is_fpreg.lo aarch64/regname.lo mi/Gdyn-extract.lo mi/Gdyn-remote.lo mi/Gfind_dynamic_proc_info.lo mi/Gget_accessors.lo mi/Gget_proc_info_by_ip.lo mi/Gget_proc_name.lo mi/Gput_dynamic_unwind_info.lo mi/Gdestroy_addr_space.lo mi/Gget_reg.lo mi/Gset_reg.lo mi/Gget_fpreg.lo mi/Gset_fpreg.lo mi/Gset_caching_policy.lo mi/Gset_cache_size.lo aarch64/Gapply_reg_state.lo aarch64/Greg_states_iterate.lo aarch64/Gcreate_addr_space.lo aarch64/Gget_proc_info.lo aarch64/Gget_save_loc.lo aarch64/Gglobal.lo aarch64/Ginit.lo aarch64/Ginit_local.lo aarch64/Ginit_remote.lo aarch64/Gis_signal_frame.lo aarch64/Gregs.lo aarch64/Gresume.lo aarch64/Gstash_frame.lo aarch64/Gstep.lo aarch64/Gtrace.lo libunwind-dwarf-generic.la libunwind-elf64.la libunwind.la -lc 
libtool: link: aarch64-openwrt-linux-gcc -shared  -fPIC -DPIC  .libs/os-linux.o .libs/dl-iterate-phdr.o mi/.libs/init.o mi/.libs/flush_cache.o mi/.libs/mempool.o mi/.libs/strerror.o aarch64/.libs/is_fpreg.o aarch64/.libs/regname.o mi/.libs/Gdyn-extract.o mi/.libs/Gdyn-remote.o mi/.libs/Gfind_dynamic_proc_info.o mi/.libs/Gget_accessors.o mi/.libs/Gget_proc_info_by_ip.o mi/.libs/Gget_proc_name.o mi/.libs/Gput_dynamic_unwind_info.o mi/.libs/Gdestroy_addr_space.o mi/.libs/Gget_reg.o mi/.libs/Gset_reg.o mi/.libs/Gget_fpreg.o mi/.libs/Gset_fpreg.o mi/.libs/Gset_caching_policy.o mi/.libs/Gset_cache_size.o aarch64/.libs/Gapply_reg_state.o aarch64/.libs/Greg_states_iterate.o aarch64/.libs/Gcreate_addr_space.o aarch64/.libs/Gget_proc_info.o aarch64/.libs/Gget_save_loc.o aarch64/.libs/Gglobal.o aarch64/.libs/Ginit.o aarch64/.libs/Ginit_local.o aarch64/.libs/Ginit_remote.o aarch64/.libs/Gis_signal_frame.o aarch64/.libs/Gregs.o aarch64/.libs/Gresume.o aarch64/.libs/Gstash_frame.o aarch64/.libs/Gstep.o aarch64/.libs/Gtrace.o  -Wl,--whole-archive ./.libs/libunwind-dwarf-generic.a ./.libs/libunwind-elf64.a -Wl,--no-whole-archive  -Wl,-rpath -Wl,/disk1/debai/Applications/libunwind/src/.libs ./.libs/libunwind.so -lc  -g -O2 -nostartfiles   -Wl,-soname -Wl,libunwind-aarch64.so.8 -o .libs/libunwind-aarch64.so.8.0.1
/disk1/debai/H1/toolchain/R329/linux-x86/aarch64/toolchain-sunxi-glibc/toolchain/bin/../lib/gcc/aarch64-openwrt-linux-gnu/6.4.1/../../../../aarch64-openwrt-linux-gnu/bin/ld: error in ./.libs/libunwind-dwarf-generic.a(Gexpr.o)(.eh_frame); no .eh_frame_hdr table will be created.
/disk1/debai/H1/toolchain/R329/linux-x86/aarch64/toolchain-sunxi-glibc/toolchain/bin/../lib/gcc/aarch64-openwrt-linux-gnu/6.4.1/../../../../aarch64-openwrt-linux-gnu/bin/ld: error in ./.libs/libunwind-dwarf-generic.a(Gfde.o)(.eh_frame); no .eh_frame_hdr table will be created.
/disk1/debai/H1/toolchain/R329/linux-x86/aarch64/toolchain-sunxi-glibc/toolchain/bin/../lib/gcc/aarch64-openwrt-linux-gnu/6.4.1/../../../../aarch64-openwrt-linux-gnu/bin/ld: error in ./.libs/libunwind-dwarf-generic.a(Gparser.o)(.eh_frame); no .eh_frame_hdr table will be created.
/disk1/debai/H1/toolchain/R329/linux-x86/aarch64/toolchain-sunxi-glibc/toolchain/bin/../lib/gcc/aarch64-openwrt-linux-gnu/6.4.1/../../../../aarch64-openwrt-linux-gnu/bin/ld: error in ./.libs/libunwind-dwarf-generic.a(Gpe.o)(.eh_frame); no .eh_frame_hdr table will be created.
/disk1/debai/H1/toolchain/R329/linux-x86/aarch64/toolchain-sunxi-glibc/toolchain/bin/../lib/gcc/aarch64-openwrt-linux-gnu/6.4.1/../../../../aarch64-openwrt-linux-gnu/bin/ld: error in ./.libs/libunwind-dwarf-generic.a(Gfind_proc_info-lsb.o)(.eh_frame); no .eh_frame_hdr table will be created.
/disk1/debai/H1/toolchain/R329/linux-x86/aarch64/toolchain-sunxi-glibc/toolchain/bin/../lib/gcc/aarch64-openwrt-linux-gnu/6.4.1/../../../../aarch64-openwrt-linux-gnu/bin/ld: error in ./.libs/libunwind-dwarf-generic.a(Gfind_unwind_table.o)(.eh_frame); no .eh_frame_hdr table will be created.
/disk1/debai/H1/toolchain/R329/linux-x86/aarch64/toolchain-sunxi-glibc/toolchain/bin/../lib/gcc/aarch64-openwrt-linux-gnu/6.4.1/../../../../aarch64-openwrt-linux-gnu/bin/ld: error in ./.libs/libunwind-dwarf-generic.a(global.o)(.eh_frame); no .eh_frame_hdr table will be created.
/disk1/debai/H1/toolchain/R329/linux-x86/aarch64/toolchain-sunxi-glibc/toolchain/bin/../lib/gcc/aarch64-openwrt-linux-gnu/6.4.1/../../../../aarch64-openwrt-linux-gnu/bin/ld: error in ./.libs/libunwind-elf64.a(elf64.o)(.eh_frame); no .eh_frame_hdr table will be created.
libtool: link: (cd ".libs" && rm -f "libunwind-aarch64.so.8" && ln -s "libunwind-aarch64.so.8.0.1" "libunwind-aarch64.so.8")
libtool: link: (cd ".libs" && rm -f "libunwind-aarch64.so" && ln -s "libunwind-aarch64.so.8.0.1" "libunwind-aarch64.so")
libtool: link: (cd .libs/libunwind-aarch64.lax/libunwind-dwarf-generic.a && aarch64-openwrt-linux-ar x "/disk1/debai/Applications/libunwind/src/./.libs/libunwind-dwarf-generic.a")
libtool: link: (cd .libs/libunwind-aarch64.lax/libunwind-elf64.a && aarch64-openwrt-linux-ar x "/disk1/debai/Applications/libunwind/src/./.libs/libunwind-elf64.a")
libtool: link: aarch64-openwrt-linux-ar cru .libs/libunwind-aarch64.a  os-linux.o dl-iterate-phdr.o mi/init.o mi/flush_cache.o mi/mempool.o mi/strerror.o aarch64/is_fpreg.o aarch64/regname.o mi/Gdyn-extract.o mi/Gdyn-remote.o mi/Gfind_dynamic_proc_info.o mi/Gget_accessors.o mi/Gget_proc_info_by_ip.o mi/Gget_proc_name.o mi/Gput_dynamic_unwind_info.o mi/Gdestroy_addr_space.o mi/Gget_reg.o mi/Gset_reg.o mi/Gget_fpreg.o mi/Gset_fpreg.o mi/Gset_caching_policy.o mi/Gset_cache_size.o aarch64/Gapply_reg_state.o aarch64/Greg_states_iterate.o aarch64/Gcreate_addr_space.o aarch64/Gget_proc_info.o aarch64/Gget_save_loc.o aarch64/Gglobal.o aarch64/Ginit.o aarch64/Ginit_local.o aarch64/Ginit_remote.o aarch64/Gis_signal_frame.o aarch64/Gregs.o aarch64/Gresume.o aarch64/Gstash_frame.o aarch64/Gstep.o aarch64/Gtrace.o  .libs/libunwind-aarch64.lax/libunwind-dwarf-generic.a/Gexpr.o .libs/libunwind-aarch64.lax/libunwind-dwarf-generic.a/Gfde.o .libs/libunwind-aarch64.lax/libunwind-dwarf-generic.a/Gfind_proc_info-lsb.o .libs/libunwind-aarch64.lax/libunwind-dwarf-generic.a/Gfind_unwind_table.o .libs/libunwind-aarch64.lax/libunwind-dwarf-generic.a/Gparser.o .libs/libunwind-aarch64.lax/libunwind-dwarf-generic.a/Gpe.o .libs/libunwind-aarch64.lax/libunwind-dwarf-generic.a/global.o  .libs/libunwind-aarch64.lax/libunwind-elf64.a/elf64.o 
aarch64-openwrt-linux-ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: aarch64-openwrt-linux-gnu-strip .libs/libunwind-aarch64.a
libtool: link: rm -fr .libs/libunwind-aarch64.lax
libtool: link: ( cd ".libs" && rm -f "libunwind-aarch64.la" && ln -s "../libunwind-aarch64.la" "libunwind-aarch64.la" )
depbase=`echo setjmp/longjmp.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CC   --mode=compile aarch64-openwrt-linux-gcc -DHAVE_CONFIG_H -I. -I../include  -I../include -I../include/tdep-aarch64 -I. -D_GNU_SOURCE -DNDEBUG  -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -MT setjmp/longjmp.lo -MD -MP -MF $depbase.Tpo -c -o setjmp/longjmp.lo setjmp/longjmp.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  aarch64-openwrt-linux-gcc -DHAVE_CONFIG_H -I. -I../include -I../include -I../include/tdep-aarch64 -I. -D_GNU_SOURCE -DNDEBUG -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -MT setjmp/longjmp.lo -MD -MP -MF setjmp/.deps/longjmp.Tpo -c setjmp/longjmp.c  -fPIC -DPIC -o setjmp/.libs/longjmp.o
libtool: compile:  aarch64-openwrt-linux-gcc -DHAVE_CONFIG_H -I. -I../include -I../include -I../include/tdep-aarch64 -I. -D_GNU_SOURCE -DNDEBUG -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -MT setjmp/longjmp.lo -MD -MP -MF setjmp/.deps/longjmp.Tpo -c setjmp/longjmp.c -o setjmp/longjmp.o >/dev/null 2>&1
depbase=`echo setjmp/siglongjmp.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CC   --mode=compile aarch64-openwrt-linux-gcc -DHAVE_CONFIG_H -I. -I../include  -I../include -I../include/tdep-aarch64 -I. -D_GNU_SOURCE -DNDEBUG  -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -MT setjmp/siglongjmp.lo -MD -MP -MF $depbase.Tpo -c -o setjmp/siglongjmp.lo setjmp/siglongjmp.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  aarch64-openwrt-linux-gcc -DHAVE_CONFIG_H -I. -I../include -I../include -I../include/tdep-aarch64 -I. -D_GNU_SOURCE -DNDEBUG -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -MT setjmp/siglongjmp.lo -MD -MP -MF setjmp/.deps/siglongjmp.Tpo -c setjmp/siglongjmp.c  -fPIC -DPIC -o setjmp/.libs/siglongjmp.o
libtool: compile:  aarch64-openwrt-linux-gcc -DHAVE_CONFIG_H -I. -I../include -I../include -I../include/tdep-aarch64 -I. -D_GNU_SOURCE -DNDEBUG -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -MT setjmp/siglongjmp.lo -MD -MP -MF setjmp/.deps/siglongjmp.Tpo -c setjmp/siglongjmp.c -o setjmp/siglongjmp.o >/dev/null 2>&1
depbase=`echo aarch64/siglongjmp.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool    --mode=compile aarch64-openwrt-linux-gcc -DHAVE_CONFIG_H -I. -I../include  -I../include -I../include/tdep-aarch64 -I. -D_GNU_SOURCE -DNDEBUG -I../include -I../include/tdep-aarch64 -I. -g -O2  -D_GNU_SOURCE -DNDEBUG -MT aarch64/siglongjmp.lo -MD -MP -MF $depbase.Tpo -c -o aarch64/siglongjmp.lo aarch64/siglongjmp.S &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  aarch64-openwrt-linux-gcc -DHAVE_CONFIG_H -I. -I../include -I../include -I../include/tdep-aarch64 -I. -D_GNU_SOURCE -DNDEBUG -I../include -I../include/tdep-aarch64 -I. -g -O2 -D_GNU_SOURCE -DNDEBUG -MT aarch64/siglongjmp.lo -MD -MP -MF aarch64/.deps/siglongjmp.Tpo -c aarch64/siglongjmp.S  -fPIC -DPIC -o aarch64/.libs/siglongjmp.o
libtool: compile:  aarch64-openwrt-linux-gcc -DHAVE_CONFIG_H -I. -I../include -I../include -I../include/tdep-aarch64 -I. -D_GNU_SOURCE -DNDEBUG -I../include -I../include/tdep-aarch64 -I. -g -O2 -D_GNU_SOURCE -DNDEBUG -MT aarch64/siglongjmp.lo -MD -MP -MF aarch64/.deps/siglongjmp.Tpo -c aarch64/siglongjmp.S -o aarch64/siglongjmp.o >/dev/null 2>&1
/bin/sh ../libtool  --tag=CC   --mode=link aarch64-openwrt-linux-gcc  -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -XCClinker -nostartfiles -version-info 0:0:0  -o libunwind-setjmp.la -rpath /usr/local/lib setjmp/longjmp.lo setjmp/siglongjmp.lo aarch64/siglongjmp.lo             libunwind-elf64.la libunwind-aarch64.la libunwind.la -lc 
libtool: link: aarch64-openwrt-linux-gcc -shared  -fPIC -DPIC  setjmp/.libs/longjmp.o setjmp/.libs/siglongjmp.o aarch64/.libs/siglongjmp.o  -Wl,--whole-archive ./.libs/libunwind-elf64.a -Wl,--no-whole-archive  -Wl,-rpath -Wl,/disk1/debai/Applications/libunwind/src/.libs ./.libs/libunwind-aarch64.so ./.libs/libunwind.so -lc  -g -O2 -nostartfiles   -Wl,-soname -Wl,libunwind-setjmp.so.0 -o .libs/libunwind-setjmp.so.0.0.0
/disk1/debai/H1/toolchain/R329/linux-x86/aarch64/toolchain-sunxi-glibc/toolchain/bin/../lib/gcc/aarch64-openwrt-linux-gnu/6.4.1/../../../../aarch64-openwrt-linux-gnu/bin/ld: error in ./.libs/libunwind-elf64.a(elf64.o)(.eh_frame); no .eh_frame_hdr table will be created.
libtool: link: (cd ".libs" && rm -f "libunwind-setjmp.so.0" && ln -s "libunwind-setjmp.so.0.0.0" "libunwind-setjmp.so.0")
libtool: link: (cd ".libs" && rm -f "libunwind-setjmp.so" && ln -s "libunwind-setjmp.so.0.0.0" "libunwind-setjmp.so")
libtool: link: (cd .libs/libunwind-setjmp.lax/libunwind-elf64.a && aarch64-openwrt-linux-ar x "/disk1/debai/Applications/libunwind/src/./.libs/libunwind-elf64.a")
copying selected object files to avoid basename conflicts...
libtool: link: ln aarch64/siglongjmp.o .libs/libunwind-setjmp.lax/lt1-siglongjmp.o || cp aarch64/siglongjmp.o .libs/libunwind-setjmp.lax/lt1-siglongjmp.o
libtool: link: aarch64-openwrt-linux-ar cru .libs/libunwind-setjmp.a setjmp/longjmp.o setjmp/siglongjmp.o .libs/libunwind-setjmp.lax/lt1-siglongjmp.o .libs/libunwind-setjmp.lax/libunwind-elf64.a/elf64.o
aarch64-openwrt-linux-ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: aarch64-openwrt-linux-gnu-strip .libs/libunwind-setjmp.a
libtool: link: rm -fr .libs/libunwind-setjmp.lax .libs/libunwind-setjmp.lax
libtool: link: ( cd ".libs" && rm -f "libunwind-setjmp.la" && ln -s "../libunwind-setjmp.la" "libunwind-setjmp.la" )
make[2]: Leaving directory '/disk1/debai/Applications/libunwind/src'
make[1]: Leaving directory '/disk1/debai/Applications/libunwind/src'
Making all in tests
make[1]: Entering directory '/disk1/debai/Applications/libunwind/tests'
depbase=`echo forker.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
aarch64-openwrt-linux-gcc -DHAVE_CONFIG_H -I. -I../include  -I../include -D_GNU_SOURCE -DNDEBUG -fno-optimize-sibling-calls -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -MT forker.o -MD -MP -MF $depbase.Tpo -c -o forker.o forker.c &&\
mv -f $depbase.Tpo $depbase.Po
/bin/sh ../libtool  --tag=CC   --mode=link aarch64-openwrt-linux-gcc -fno-optimize-sibling-calls -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -static  -o forker forker.o  
libtool: link: aarch64-openwrt-linux-gcc -fno-optimize-sibling-calls -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -o forker forker.o 
depbase=`echo Gperf-simple.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
aarch64-openwrt-linux-gcc -DHAVE_CONFIG_H -I. -I../include  -I../include -D_GNU_SOURCE -DNDEBUG -fno-optimize-sibling-calls -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -MT Gperf-simple.o -MD -MP -MF $depbase.Tpo -c -o Gperf-simple.o Gperf-simple.c &&\
mv -f $depbase.Tpo $depbase.Po
/bin/sh ../libtool  --tag=CC   --mode=link aarch64-openwrt-linux-gcc -fno-optimize-sibling-calls -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__   -o Gperf-simple Gperf-simple.o ../src/libunwind-aarch64.la ../src/libunwind.la 
libtool: link: aarch64-openwrt-linux-gcc -fno-optimize-sibling-calls -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -o .libs/Gperf-simple Gperf-simple.o  ../src/.libs/libunwind-aarch64.so ../src/.libs/libunwind.so
../src/.libs/libunwind.so: undefined reference to `_ULaarch64_dwarf_find_proc_info'
../src/.libs/libunwind.so: undefined reference to `_ULaarch64_dwarf_make_proc_info'
../src/.libs/libunwind-aarch64.so: undefined reference to `_Uaarch64_dwarf_flush_rs_cache'
../src/.libs/libunwind.so: undefined reference to `_ULaarch64_dwarf_apply_reg_state'
../src/.libs/libunwind.so: undefined reference to `_ULaarch64_dwarf_put_unwind_info'
../src/.libs/libunwind-aarch64.so: undefined reference to `_Uaarch64_dwarf_search_unwind_table'
../src/.libs/libunwind-aarch64.so: undefined reference to `_Uaarch64_dwarf_make_proc_info'
../src/.libs/libunwind-aarch64.so: undefined reference to `_Uaarch64_dwarf_apply_reg_state'
../src/.libs/libunwind.so: undefined reference to `_ULaarch64_dwarf_reg_states_iterate'
../src/.libs/libunwind.so: undefined reference to `_ULaarch64_dwarf_step'
../src/.libs/libunwind.so: undefined reference to `_ULaarch64_dwarf_search_unwind_table'
../src/.libs/libunwind-aarch64.so: undefined reference to `_Uaarch64_dwarf_reg_states_iterate'
../src/.libs/libunwind-aarch64.so: undefined reference to `_Uaarch64_dwarf_init'
../src/.libs/libunwind-aarch64.so: undefined reference to `_Uelf64_get_proc_name'
../src/.libs/libunwind-aarch64.so: undefined reference to `_Uaarch64_dwarf_find_proc_info'
../src/.libs/libunwind.so: undefined reference to `_ULaarch64_dwarf_flush_rs_cache'
../src/.libs/libunwind-aarch64.so: undefined reference to `_Uaarch64_dwarf_step'

feel confused about this problem,  really want to find the reason. Thanks again!!!!

**Comment by bregma** [comment]
Closing issue as due to local build environment issue.
