### ISSUE TITLE
unw_is_signal_frame identifies signal handler trampoline on AArch64 Linux

### ISSUE THREAD

**Issue by sfc-gh-sgiesecke** [libunwind/libunwind#343]
The program below fails on AArch64 Linux with the following output:
```
ip = ffffa8c577ec, sp = fffff0db95b0 offset = ffffa8c59000 unw_get_proc_name =  dladdr_name = __kernel_rt_sigreturn is_signal_frame = 1
frame  doesn't match expected frame gsignal
ip = ffffa898c238, sp = fffff0dba810 offset = 4c unw_get_proc_name = gsignal dladdr_name = gsignal is_signal_frame = 0
ip = 400928, sp = fffff0dba830 offset = 58 unw_get_proc_name = main dladdr_name = (null) is_signal_frame = 0
ip = ffffa8978724, sp = fffff0dba8e0 offset = f0 unw_get_proc_name = __libc_start_main dladdr_name = __libc_start_main is_signal_frame = 0
ip = 400964, sp = fffff0dbaa20 offset = 2c unw_get_proc_name = _start dladdr_name = (null) is_signal_frame = 0
ip = 400964, sp = fffff0dbaa20 offset = 2c unw_get_proc_name = _start dladdr_name = (null) is_signal_frame = 0
Failed to find all frames i:0 != names_count:1
```

My expectation is that the `gsignal` frame is identified as the signal frame by `unw_get_proc_name`, as it is the case on `x86_64`, rather than the "signal handler trampoline" function `__kernel_rt_sigreturn`.

(Furthermore, `unw_get_proc_name` doesn't return a name for the signal handler trampoline, while `dladdr` does, not sure if that's expected because it's a vDSO function)

```
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <string.h>
#include <execinfo.h>
#include <sys/types.h>
#include <sys/ucontext.h>
#include <unistd.h>
#include <dlfcn.h>

#ifdef HAVE_SYS_PTRACE_H
#include <sys/ptrace.h>
#endif

#define UNW_LOCAL_ONLY
#include <libunwind.h>

/*
 * unwind in the signal handler checking the backtrace is correct
 * after a bad jump.
 */
void handle_sigsegv(int signal, siginfo_t *info, void *ucontext)
{
  /*
   * 0 = success
   * !0 = general failure
   * 77 = test skipped
   * 99 = complete failure
   */
  int test_status = 0;
  unw_cursor_t cursor; unw_context_t uc;
  unw_word_t ip, sp, offset;
  char name_unw_get_proc_name[1000];
  Dl_info dl_info;

  int i = 0;
  char *names[] = {
    "gsignal",
  };
  int names_count = sizeof(names) / sizeof(*names);

  unw_getcontext(&uc);
  unw_init_local(&cursor, &uc);

  while (unw_step(&cursor) > 0)
    {
      int found_signal_frame = 0;
      if (unw_is_signal_frame(&cursor))
        {
          found_signal_frame = 1;
        }
        unw_get_reg(&cursor, UNW_REG_IP, &ip);
        unw_get_reg(&cursor, UNW_REG_SP, &sp);

        memset(name_unw_get_proc_name, 0, sizeof(char) * 1000);
        unw_get_proc_name(&cursor, name_unw_get_proc_name, sizeof(char) * 1000, &offset);

        dladdr((const void*)ip, &dl_info);

        printf("ip = %lx, sp = %lx offset = %lx unw_get_proc_name = %s dladdr_name = %s is_signal_frame = %d\n", (long) ip, (long) sp, (long) offset, name_unw_get_proc_name, dl_info.dli_sname, found_signal_frame);
      if (found_signal_frame)
        {
          if (i < names_count)
            {
              if (strcmp(names[i], name_unw_get_proc_name) != 0)
                {
                  test_status = 1;
                  printf("frame %s doesn't match expected frame %s\n", name_unw_get_proc_name, names[i]);
                }
              else
                {
                  i += 1;
                }
            }
        }
    }

  if (i != names_count) //Make sure we found all the frames!
    {
      printf("Failed to find all frames i:%d != names_count:%d\n", i, names_count);
      test_status = 1;
    }

  /*return test_status to test harness*/
  exit(test_status);
}

int main(int argc, char *argv[])
{
  struct sigaction sa;
  memset(&sa, 0, sizeof(sa));
  sa.sa_sigaction = handle_sigsegv;
  sa.sa_flags = SA_SIGINFO;
  sigaction(SIGSEGV, &sa, NULL);

  gsignal(SIGSEGV);

  /*
   * 99 is the hard error exit status for automake tests:
   * https://www.gnu.org/software/automake/manual/html_node/Scripts_002dbased-Testsuites.html#Scripts_002dbased-Testsuites
   * If we dont end up in the signal handler something went horribly wrong.
   */
  return 99;
}
```

**Comment by bregma** [comment]
Are you saying you expect the unwinder to hide certain frames (eg. the signal handler trampoline)?

**Comment by sfc-gh-sgiesecke** [comment]
> Are you saying you expect the unwinder to hide certain frames (eg. the signal handler trampoline)?

@bregma No, that's not what I meant. I think it's expected (maybe not necessary though? not sure about that) that the signal handler trampoline is identified as _a_ frame, but not that it's the one that's identified as the _signal_ frame. My expectation was that the _signal_ frame should be the same independent of the architecture (where applicable). The `gsignal` frame is there on both x86_64 and aarch64, but it's only identified as the `signal` frame on x86_64. 

Or maybe I misunderstand what the meaning of `unw_is_signal_frame` is. The manpage says
> a signal frame is a frame that was created in response to a potentially asynchronous interruption

which is kind of ambiguous. If that (and the difference between architectures) is the expected behaviour according to that, maybe that should be clarified in the manpage.

**Comment by bregma** [comment]
`gsignal()` (aka `raise()`) *raises* the signal. It's not the signal frame, which would be the frame the OS jumps to to *handle* the signal.

On x86_64, the Linux kernel passes an indicator to the signal handler through the context structure that's treated specially by `dwarf_step()` and you don't need to wind further back than the callback function. For other architectures, `unw_step()` needs to check the code around the call point, looking for a specific signature to recognize a trampoline. By that point it's in the trampoline frame and already unwound past the callback function.

Different ABIs for different architectures, that's all.

**Comment by sfc-gh-sgiesecke** [comment]
Ok, makes sense. Then I was under a wrong impression what "signal frame" means. Is `unw_is_signal_frame` then useful for the user of libunwind at all (in a platform-independent way)? Or is this more relevant for the internals of libunwind itself?

**Comment by lemul** [comment]
> `gsignal()` (aka `raise()`) _raises_ the signal. It's not the signal frame, which would be the frame the OS jumps to to _handle_ the signal.
> 
> On x86_64, the Linux kernel passes an indicator to the signal handler through the context structure that's treated specially by `dwarf_step()` and you don't need to wind further back than the callback function. For other architectures, `unw_step()` needs to check the code around the call point, looking for a specific signature to recognize a trampoline. By that point it's in the trampoline frame and already unwound past the callback function.
> 
> Different ABIs for different architectures, that's all.

In my POV this is a bug due to .cfi_signal_frame directive mark **current function** as signal trampoline. Not a previous frame.
