### ISSUE TITLE
Could not dump full backtrace in the signal handler

### ISSUE THREAD

**Issue by HemingT** [libunwind/libunwind#346]
My OS: x86-64 openwrt 21.0.2
GCC: x86_64-openwrt-linux-musl-gcc (OpenWrt GCC 8.4.0 r16325-88151b8303) 8.4.0

Purpose: To dump full backtrace when crashed, especially the crash happened in which function

Result: I found that the backtrace did not include the function which introduced the crash.

I attached an example of my program.

the crash would happen in the function crash_func 
in the signal handler, I dump the backtrace.  the backtrace did not include the func crash_func.
It's very strange. Is there any mistake in my code? Could you please give some suggestion? Thank you!

 cat /tmp/unwind.txt
_Z25exception_default_handleriP9siginfo_tPv
sigwaitinfo
_Z9test_funcv
main
libc_start_main_stage2

```

#define UNW_LOCAL_ONLY
#include <libunwind.h>
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>


void do_backtrace()
{
    unw_cursor_t cursor;
    unw_context_t context;

    unw_getcontext(&context);
    unw_init_local(&cursor, &context);
    char buf[4096];
    int len = 0;
    memset(buf, 0, sizeof(buf));

    while(unw_step(&cursor))
    {
        unw_word_t ip, sp, off;

        unw_get_reg(&cursor, UNW_REG_IP, &ip);
        unw_get_reg(&cursor, UNW_REG_SP, &sp);

        char symbol[1024] = {0};
        unw_get_proc_name(&cursor, symbol, sizeof(symbol), &off);
        strcat(buf, symbol);
        strcat(buf, "\n");
    }

    u_int32_t fd;
    fd = open("/tmp/unwind.txt", O_CREAT|O_RDWR);
    if(fd != -1)
    {
        write(fd, buf, strlen(buf));
    }
    close(fd);

}

int crash_func()
{
    printf("enter into crash_func\n");
    char *pStr= NULL;
    memcpy(pStr, "Hello", strlen("Hello"));
    return 1;

}

int test_func()
{
    printf("entern into test_fuc\n");
    crash_func();
    return 0;
}


void exception_default_handler(int signo, siginfo_t *info, void *context)
{
    do_backtrace();

    exit(1);
}

#define SETSIG(sa, sig, func) \
    {   \
        memset( &sa, 0, sizeof( struct sigaction ) ); \
        sa.sa_sigaction = func; \
        sa.sa_flags = SA_RESTART | SA_SIGINFO; \
        sigaction(sig, &sa, 0L); \
    }

int main()
{
    struct sigaction sa;

    SETSIG(sa, SIGSEGV, exception_default_handler);

    test_func();

    return 0;
}
```

**Comment by HemingT** [comment]
libunwind version: 1.6.2

**Comment by HemingT** [comment]
@am11  @djwatson Could you please have a look? Thank you!

**Comment by am11** [comment]
@HemingT, in case you cannot reproduce this issue on alpine and only openwrt, then the first thing I'd try is linking with `libucontext-dev` (rather than using in-tree functionality of get/set ucontext). See https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/main/libunwind/APKBUILD#L29. The source code of libucontext resides in https://github.com/kaniini/libucontext.

**Comment by HemingT** [comment]
@am11 Thank you very much for your quick feedback. I try to do as you suggest. but the result is the same.

root@Controller_Env:/hemingt_repo# ldd /tmp/dump_backtrace
        /lib/ld-musl-x86_64.so.1 (0x7fb9b6b93000)
        libunwind.so.8 => /usr/lib/libunwind.so.8 (0x7fb9b6b7c000)
        libunwind-x86_64.so.8 => /usr/lib/libunwind-x86_64.so.8 (0x7fb9b6b62000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x7fb9b6b47000)
        libucontext.so.1 => /usr/lib/libucontext.so.1 (0x7fb9b6b42000)
        libz.so.1 => /usr/lib/libz.so.1 (0x7fb9b6b2e000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7fb9b6b1a000)
        libc.so => /lib/ld-musl-x86_64.so.1 (0x7fb9b6b93000)
root@Controller_Env:/hemingt_repo#
root@Controller_Env:/hemingt_repo#
root@Controller_Env:/hemingt_repo# ldd /usr/lib/libunwind.so
        ldd (0x7f368171f000)
        libucontext.so.1 => /usr/lib/libucontext.so.1 (0x7f3681703000)
        libc.so => ldd (0x7f368171f000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7f36816ef000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x7f36816d4000)
        libz.so.1 => /usr/lib/libz.so.1 (0x7f36816c0000)
root@Controller_Env:/hemingt_repo# ldd /usr/lib/libunwind-x86_64.so
        ldd (0x7f7235592000)
        libunwind.so.8 => /hemingt_repo/host/libunwind/src/.libs/libunwind.so.8 (0x7f7235561000)
        libucontext.so.1 => /usr/lib/libucontext.so.1 (0x7f723555c000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7f7235548000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x7f723552d000)
        libz.so.1 => /usr/lib/libz.so.1 (0x7f7235519000)
        libc.so => ldd (0x7f7235592000)

cat /tmp/unwind.txt
_Z25exception_default_handleriP9siginfo_tPv
sigwaitinfo
_Z9test_funcv
main
libc_start_main_stage2

**Comment by HemingT** [comment]
[dump_backtrace-objdump.txt](https://github.com/libunwind/libunwind/files/8379386/dump_backtrace-objdump.txt)
[dump_backtrace-cpp.txt](https://github.com/libunwind/libunwind/files/8379396/dump_backtrace-cpp.txt)

**Comment by HemingT** [comment]
@am11  Hello,
my question is:
for x86-64, libunwind has provided its implementation of getcontext/setcontext, how to let libunwind use the version of libucontext' getcontext/setcontext? Only just to link libucontext library during libunwind compilation? is there other steps need to do?

**Comment by lemul** [comment]
It should not if memcpy is a macros, try:
    do
    {
  ...
    }  while(unw_step(&cursor) > 0)

**Comment by bregma** [comment]
In the original case, `crash_func()` contains obvious undefined behaviour, which can cause the compiler to eliminate the function (or do anything else). Have you verified the function is present in the generated assembly, complete with the `.cfi` directives used to generate unwind tables? That would be the first step to analyzing this problem.
