### ISSUE TITLE
Android Build error help wanted 

### ISSUE THREAD

**Issue by Saikatsaha1996** [libunwind/libunwind#349]
![Screenshot_2022-04-01-22-23-03-020_com termux](https://user-images.githubusercontent.com/72664192/161308048-3370e924-d73d-4a25-baa5-2ec92aebb617.jpg)

**Comment by bregma** [comment]
Are you building natively on an Android host? It should autodetect that and not define **LIBCRTS** during the configure run. Try explicitly add the appropriate `--host=` argument to configure and see if that makes a difference.

**Comment by Saikatsaha1996** [comment]
> Are you building natively on an Android host? It should autodetect that and not define **LIBCRTS** during the configure run. Try explicitly add the appropriate `--host=` argument to configure and see if that makes a difference.

Thank you for your response
Done already 😊!

**Comment by Saikatsaha1996** [comment]
Can't compile help wanted

![Screenshot_2022-12-28-23-10-49-026_com termux](https://user-images.githubusercontent.com/72664192/209851385-f4b00d60-17bd-41b1-b37b-9981e8bd80fd.jpg)

**Comment by Saikatsaha1996** [comment]
My cmmd line

```
./configure --prefix=$PREFIX OS=android --disable-tests --disable-coredump
```
Error

`ld.lld: error: unable to find library -lgcc_s`

**Comment by Saikatsaha1996** [comment]
Solved with!
```
./configure --prefix=$PREFIX OS=android --disable-tests --disable-coredump --host=aarch64 --target=aarch64
```
