### ISSUE TITLE
https://git.savannah.gnu.org/git/libunwind.git is out of sync with this github repo

### ISSUE THREAD

**Issue by cheese** [libunwind/libunwind#351]
Both master and v1.6-stable branches on savannah lag behind this github repo. Downstream projects that track the repo on savannah will miss the latest release.

Can you keep the repo on savannah up-to-date? Or just announce the repo on savannah obsoleted?

**Comment by djwatson** [comment]
These should be in sync now, but yes I should announce/ remove the savannah repo soon.
