### ISSUE TITLE
'#include_next <unwind.h>' statement in unwind.h fails

### ISSUE THREAD

**Issue by yurivict** [libunwind/libunwind#394]
On FreeBSD systems without system-installed ```unwind.h``` ```#include_next <unwind.h>``` fails because there is no other ```unwind.h``` available.

Why is this statement present in ```/usr/local/include/unwind.h```?

Version: 20211201
OS: FreeBSD 13.1

**Comment by bregma** [comment]
Are you sure you're looking at a `/usr/local/include/unwind.h` supplied by [this](https://github.com/libunwind/libunwind/blob/master/include/unwind.h) project?

**Comment by yurivict** [comment]
Yes. libunwind is installed by the FreeBSD port ```devel/libunwind```, version 1.6.2 released on 20211201.

**Comment by bregma** [comment]
[This project does not have any headers that contain `#include_next`](https://github.com/libunwind/libunwind/search?q=include_next). [ The FreeBSD port has its own `unwind.h`](https://cgit.freebsd.org/ports/tree/devel/libunwind/files) that contains `#include_next`. If you have questions about code from FreeBSD you need to ask the FreeBSD developers. We can only answer questions related to code in the libunwind project here.
