### ISSUE TITLE
failed to cross build libunwind for riscv64

### ISSUE THREAD

**Issue by unicornx** [libunwind/libunwind#395]
Hello, I see https://github.com/libunwind/libunwind/pull/267 mentiond riscv has been supported, so I want to have a try.

Following is what I do and I am using libunwind-1.6.2, and gcc for riscv is 12.1.0
```
mkdir build && cd build
CROSS_COMPILE=riscv64-unknown-linux-gnu- ../libunwind-1.6.2/configure --prefix=/home/u/ws/temp/test-libunwind/install --target=riscv64
make
```
But build failed and reported many error such as:
```
../../libunwind-1.6.2/include/libunwind-riscv.h:65:3: error: #error "Unsupported RISC-V floating-point size"
 # error "Unsupported RISC-V floating-point size"
   ^~~~~
In file included from ../../libunwind-1.6.2/include/libunwind-riscv.h:174:0,
                 from ../include/libunwind.h:38,
                 from ../../libunwind-1.6.2/include/libunwind_i.h:51,
                 from ../../libunwind-1.6.2/src/mi/init.c:26:
../../libunwind-1.6.2/include/libunwind-dynamic.h:93:5: error: unknown type name ‘unw_word_t’
     unw_word_t val;                     /* auxiliary value */
     ^~~~~~~~~~
```

Has libunwind supportted risc-v ?

**Comment by dlan17** [comment]
we've actually tested on Gentoo Linux with native compiling (not cross-compiling..)

and, after take a look at configure, it should just passing "--target=riscv"

**Comment by dlan17** [comment]
also set floatpoint abi flags explicitly? for example, pass CFLAGS=" -O2 -mabi=lp64d" , CXXFLAGS=" -O2 -mabi=lp64d"

**Comment by unicornx** [comment]
> we've actually tested on Gentoo Linux with native compiling (not cross-compiling..)
> 
> and, after take a look at configure, it should just passing "--target=riscv"

riscv does not work, what version of libunwind are you using?

```
$ CROSS_COMPILE=riscv64-unknown-linux-gnu- ../libunwind-1.6.2/configure --prefix=/home/u/ws/temp/test-libunwind/install --target=riscv
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... Invalid configuration `riscv': machine `riscv' not recognized
configure: error: /bin/bash ../libunwind-1.6.2/config/config.sub riscv failed
```

**Comment by unicornx** [comment]
I changed the configure command to 
```
../libunwind-1.6.2/configure --prefix=/home/u/ws/temp/test-libunwind/install --host=riscv64-unknown-linux-gnu
```
I can make now, but near the end of building, it reports: "undefined reference to `_Uriscv_setcontext'"
Detailed log as below:
```
libtool: link: riscv64-unknown-linux-gnu-gcc -fno-optimize-sibling-calls -g -O2 -fexceptions -Wall -Wsign-compare -D__EXTENSIONS__ -o .libs/test-coredump-unwind test-coredump-unwind.o  ../src/.libs/libunwind-coredump.so ../src/.libs/libunwind-riscv.so -Wl,-rpath -Wl,/home/u/ws/temp/test-libunwind/install/lib
/home/u/ws/test-gcc/install/lib/gcc/riscv64-unknown-linux-gnu/12.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: warning: libunwind.so.8, needed by ../src/.libs/libunwind-riscv.so, not found (try using -rpath or -rpath-link)
/home/u/ws/test-gcc/install/lib/gcc/riscv64-unknown-linux-gnu/12.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../src/.libs/libunwind-riscv.so: undefined reference to `_Uriscv_setcontext'
collect2: error: ld returned 1 exit status
Makefile:1320: recipe for target 'test-coredump-unwind' failed
make[1]: *** [test-coredump-unwind] Error 1
make[1]: Leaving directory '/home/u/ws/temp/test-libunwind/build/tests'
Makefile:612: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by dlan17** [comment]
I'm also using version 1.6.2

for using cross-compiling, you probably have to fix link path, the message already give you hint:
`riscv64-unknown-linux-gnu/bin/ld: warning: libunwind.so.8, needed by ../src/.libs/libunwind-riscv.so, not found (try using -rpath or -rpath-link)
`

for my system, you can tell _Uriscv_setcontext provided by libunwind.so.8

$ readelf -a  /usr/lib64/libunwind.so.8.0.1  |grep _Uriscv_setcontext
00000000d0f0  005c00000005 R_RISCV_JUMP_SLOT 000000000000427a _Uriscv_setcontext + 0
    92: 000000000000427a   146 FUNC    GLOBAL DEFAULT    9 _Uriscv_setcontext

**Comment by bregma** [comment]
Our CI system [cross builds riscv64](https://github.com/libunwind/libunwind/runs/7697569874) on a Ubuntu 20.04 x86_64 build host without compilation errors. Do you see the errors if you use the same configuration options as the CI job?

**Comment by unicornx** [comment]
> Our CI system [cross builds riscv64](https://github.com/libunwind/libunwind/runs/7697569874) on a Ubuntu 20.04 x86_64 build host without compilation errors. Do you see the errors if you use the same configuration options as the CI job?

I double checked CI log and think the configuration operation is just a bit different and after I added `--build` the build continues and still failed at the same point when  linking test-coredump-unwind. Now I have to comment the building of test-coredump-unwind in `tests/Makefile.am` and work-around this problem. Then the build pass and installation is ok.

I doubt it is due to I am using a riscv gnu toolchian built by myself, but not the one apt installed. I have not got time to rootcause it, will try later when the time is right.

Thank you anyway.

**Comment by bregma** [comment]
Cross compiling is not an art but a science. There is no magic. You  need to set [both --host and --build](https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Hosts-and-Cross_002dCompilation.html) in configure otherwise it assumes build==target and setting CROSS_COMPILE is specific to using the Android NDK.
