### ISSUE TITLE
how to exclude libgcc_eh when using libunwind

### ISSUE THREAD

**Issue by unicornx** [libunwind/libunwind#405]
hi, I am using libunwind for riscv and write code to call "_Unwind_Backtrace()", but when I link the code, gcc reports "multiple definition of `_Unwind_Backtrace'", and it's due to conflict with libgcc_eh, which also define the same "_Unwind_Backtrace()".
```
/home/u/ws/test-gcc/install/lib/gcc/riscv64-unknown-linux-gnu/12.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: /home/u/ws/test-gcc/install/lib/gcc/riscv64-unknown-linux-gnu/12.1.0/libgcc_eh.a(unwind-dw2.o): in function `_Unwind_Backtrace':
/home/u/ws/test-gcc/build/build-gcc-linux-stage2/riscv64-unknown-linux-gnu/libgcc/../../../../riscv-gnu-toolchain/riscv-gcc/libgcc/unwind.inc:292: multiple definition of `_Unwind_Backtrace'; /home/u/ws/temp/test-libunwind/riscv/install/lib//libunwind.a(Backtrace.o):/home/u/ws/temp/test-libunwind/build/src/../../libunwind/src/unwind/Backtrace.c:30: first defined here
collect2: error: ld returned 1 exit status
```

Following is the command line I use to compile the code:
```
riscv64-unknown-linux-gnu-gcc ../test_libunwind_signal.c -I/home/u/ws/temp/test-libunwind/riscv/install/include -L/home/u/ws/temp/test-libunwind/riscv/install/lib/ -lunwind-riscv -lunwind -static -fexceptions
```
The problem is I find when I try the same work for x86, the link can pass and create the a.out.

Another problem is when I compile the code, cc1 warns:
```
warning: implicit declaration of function '_Unwind_Backtrace' [-Wimplicit-function-declaration]
   49 |   _Unwind_Backtrace(FrameCounter, &count);
      |   ^~~~~~~~~~~~~~~~~
```
but I already `#include "unwind.h"` and provide "-I/home/u/ws/temp/test-libunwind/riscv/install/include", who knows what's the problem here？

Thanks in adv.

**Comment by bregma** [comment]
Your libunwind C++ exception-handling runtime is conflicting with the C++ language runtime supplied by the compiler.

I suspect using the libunwind C++ runtime is not what you really want. Building it is disabled by default for x86_64.

I suggest you pass `--disable-cxx-exceptions` (or `--enable-cxx-exceptions=no`) to disable building the C++ runtime component and see if it resolves your problem.  If that fixes the problem, `configure.ac` can be tweaked to make disabling that features the default for RISC-V too.

**Comment by unicornx** [comment]
> --disable-cxx-exceptions

I use libunwind due to I want to call `_Unwind_Backtrace()` to get stack unwinding info. Follow up your suggestions, I added `--disable-cxx-exceptions` when configure the build and seems it can pass linking. But the problem is I see the libunwind doesn't work correctly and can not unwinding the stack info. Event when I switch to call `unw_*` it still can not get the unwinding info. Unwinding can only get the top level and no deeper.

I'm afraid it is not I want.

**Comment by bregma** [comment]
If you really want to use the libunwind replacement of the C++ runtimet -- no problem, that's what it's there for -- you'll need to experiment with -nostdlib to avoid linking in the compiler-supplied runtime (libgcc_s.so, libgcc.a, libgcc_eh.a) as well as the C-language runtime (libc.so, libc.a). Then, you'll have to explicitly add libc into the appropriate _LIBADD to avoid underlinking. Check out how LIBCRTS is handled in the Makefile.am files. 

Patches are welcome.

**Comment by bregma** [comment]
Is this still an issue?

**Comment by unicornx** [comment]
I will close this issue for now, due to I'm not working on this and no more input. thanks for your feedback and tracking.
