### ISSUE TITLE
unw_is_signal_frame not implemented for FreeBSD/aarch64

### ISSUE THREAD

**Issue by sec** [libunwind/libunwind#407]
As title says, currently `unw_is_signal_frame` return `-UNW_ENOINFO` on non Linux/arm64 target - how much effort would be to implement this?

**Comment by bregma** [comment]
It shouldn't be a lot of effort but it would need to be done by someone with access to the OS/architecture. Shouldn't be too different from GNU/Linux for aarch64.

Contributions are welcome.

**Comment by sec** [comment]
Well, I can give access to OS/architecture (and any tools if needed) to someone who could contribute his skills/time if needed, but my knowledge about that topic is none :)
