### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by kasperk81** [libunwind/libunwind#446]
latest release is one year old https://github.com/libunwind/libunwind/releases/tag/v1.6.2. any timeline on 1.7?

**Comment by djwatson** [comment]
I’ll do my best to get a new release rolling in January. Thanks

**Comment by djwatson** [comment]
v1.7.0-rc1 has been branched / tagged.  Will promote to v1.7.0 after a couple weeks barring any issues.

**Comment by kasperk81** [comment]
one issue is fixed in https://github.com/libunwind/libunwind/pull/481. after merging it, please make a release from master branch that has the other fixes.

**Comment by kasperk81** [comment]
@bregma libunwind repo was maintaining once a year minor release streak. we are five months overdue (counting from 1.6.0 release date). please publish the release with 1.7.0 tag at https://github.com/libunwind/libunwind/releases
