### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by zhengshuxin** [libunwind/libunwind#452]
When running "./configure" on Ubuntu22.04, I got the below error:

...
configure: creating ./config.status
config.status: error: cannot find input file: `tests/Makefile.in'

Is the Makefile.in missing?

**Comment by bregma** [comment]
Neithe `./configure` nor `tests/Makefile.in` are found in this repository. If you're checking source out from gitlab you need to follow the build directions in the README. If you're getting the source from elsewhere, you'll need to ask them.

**Comment by zhengshuxin** [comment]
I've solved this problem by downloading libunwind from http://download.savannah.nongnu.org/releases/libunwind/.
