### ISSUE TITLE
valgrind reports UMRs due to validate_mem writing uninitialzed memory to pipe.

### ISSUE THREAD

**Issue by peadar** [libunwind/libunwind#453]
When running valgrind on a program that uses libunwind, it reports UMR errors. (Log attached)

This is caused by write_validate using the page-aligned address of the page it is attempting to validate as readable as an argument to syscall(SYS_write...). Apparently, syscall is used rather than the write() stub in libc because that circumvented the same warning with ASAN, but valgrind is clever enough to understand that SYS_write accesses memory pointed to by the arguments.
[log.txt](https://github.com/libunwind/libunwind/files/10390615/log.txt)

I have a patch that addresses this by having validate_mem use the original address that access_mem will try and access, rather than the start of that page - because we are going to read this anyway, it is, if things are functioning correctly, guaranteed to be initialized.

**Comment by bregma** [comment]
Closed by #454
