### ISSUE TITLE
Anyone can help in compiling libunwind on Ubuntu x86-64 for Android?

### ISSUE THREAD

**Issue by huangjiange** [libunwind/libunwind#47]
Anyone who can help compile libunwind on Ubuntu x86-64 for Android devices?(wanna get 32bit and 64bit so files...)
How to config OR compile with android NDK?
I have tried  ./configure --host="arm-linux-android"(also ./configure --host=arm-linux-androideabi)and make but failed...

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include -I../include -I../include/tdep-arm -I. -D_GNU_SOURCE -DNDEBUG -g -O2 -fexceptions -Wall -Wsign-compare -MT arm/is_fpreg.lo -MD -MP -MF arm/.deps/is_fpreg.Tpo -c arm/is_fpreg.c  -fPIC -DPIC -o arm/.libs/is_fpreg.o
arm/is_fpreg.c: In function '_Ux86_64_is_fpreg':
arm/is_fpreg.c:33:22: error: 'UNW_ARM_S0' undeclared (first use in this function)
   return ((regnum >= UNW_ARM_S0 && regnum <= UNW_ARM_S31)

Thanks.

**Comment by huangjiange** [comment]
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include -I../include -I../include/tdep-arm -I. -D_GNU_SOURCE -DNDEBUG -g -O2 -fexceptions -Wall -Wsign-compare -MT arm/is_fpreg.lo -MD -MP -MF arm/.deps/is_fpreg.Tpo -c arm/is_fpreg.c  -fPIC -DPIC -o arm/.libs/is_fpreg.o
arm/is_fpreg.c: In function '_Ux86_64_is_fpreg':
arm/is_fpreg.c:33:22: error: 'UNW_ARM_S0' undeclared (first use in this function)
   return ((regnum >= UNW_ARM_S0 && regnum <= UNW_ARM_S31)

**Comment by am11** [comment]
I used libunwind package by termux on Android. Their build simply calls `libunwind/autogen.sh`: https://github.com/termux/termux-packages/blob/f7159d9/packages/libunwind/build.sh.
