### ISSUE TITLE
Layout of struct fpreg has changed in FreeBSD arm

### ISSUE THREAD

**Issue by rcmcdonald91** [libunwind/libunwind#477]
https://reviews.freebsd.org/D37419

Old:
```
struct fpreg {
	unsigned int fpr_fpsr;
	fp_reg_t fpr[8];
};
```

New:
```
struct fpreg {
	__uint64_t	fpr_r[32];
	__uint32_t	fpr_fpscr;
};
```

**Comment by bregma** [comment]
- Is this ARMv7 or ARMv8?
- Is there a way to distinguish which version of FreeBSD at compile time?

**Comment by rcmcdonald91** [comment]
> * Is this ARMv7 or ARMv8?

v7

> * Is there a way to distinguish which version of FreeBSD at compile time?

Yes. https://docs.freebsd.org/en/books/porters-handbook/versions/

Specifically we want to test if `__FreeBSD_version >= 1400079`
