### ISSUE TITLE
libunwind fails to build with clang for arm32

### ISSUE THREAD

**Issue by rossburton** [libunwind/libunwind#482]
If I build libunwind 1.6.2 for 32-bit arm with clang, it fails:

```
libunwind-1.6.2/src/arm/Gtrace.c:529:7: error: call to undeclared library function 'printf' with type 'int (const char *, ...)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
       printf("XXX1\n");
```

This function has some a few `printf("XXX")` calls in, I guess indicating areas where code not finished?  I suspect these should be replaced with `Debug()` or just asserts, depending on how bad these missing codepaths are.

**Comment by arrowd** [comment]
Why does `case UNW_ARM_FRAME_SYSCALL` produce a runtime warning with `Dprint`, but `case UNW_ARM_FRAME_SIGRETURN` on FreeBSD is made to fail at the compile time?
