### ISSUE TITLE
1.7.0 package name and version in pkg-config files are broken

### ISSUE THREAD

**Issue by bertwesarg** [libunwind/libunwind#535]
First, thanks for the release, but the 1.7.0 package name is broken, it reads `libunwind-1.70.tar.gz`.

The reason is the missing `.` between `pkg_minor` and `pkg_suffix` in `mkvers`. This was changed in the 1.6 release branch 9a0de16192977b609691e824c900b628d623510b.

**Comment by bertwesarg** [comment]
No interest in fixing this?

**Comment by bregma** [comment]
It just doesn't seem worthwhile to modifiy the code and re-issue the release just because the distribution tarball name is imperfect. This will get fixed if there is some other reason to up-issue the 1.7 release.

**Comment by bertwesarg** [comment]
But others (see commit in sys-libs/libunwind) already workaround the issue. If the next release (be it 1.7.1 or 1.8.0) will be released (with the fix), they will add a second workaround again. I for myself are reluctance to add a workaround in my [buildscripts](https://gitlab.com/score-p/scorep/-/blob/master/build-config/downloads) only for this release. I also don't see any adaptation for the new 1.7 release in other meta package build systems like [spack](https://github.com/spack/spack_spack/tree/develop/var/spack/repos/builtin/packages/libunwind) or [EasyBuild](https://github.com/easybuilders/easybuild-easyconfigs/tree/main/easybuild/easyconfigs/l/libunwind). Not sure about the reasons though.

Btw, I did not noticed this either yet, but the `pgk-config` files announce themselves as version `1.70` So thats also broken, if someone requests version `1.7.0` via `pkg-config`.
