### ISSUE TITLE
build libunwind for qnx failed

### ISSUE THREAD

**Issue by huige007** [libunwind/libunwind#564]
I use following steps to compile libunwind for qnx on ~20.04.1-Ubunt
1. source qnxsdp-env.sh (which can add qnx compile tool-chain to path envioronment)
2. ./configure --host=aarch64-unknown-nto-qnx7.0.0
3. make
but I got following error message when makeing, could anyone help me to resolve it. Is there any problem in the parameters passsd to configure?

Making all in src
make[1]: Entering directory '/home/junfei/01_github/libunwind/src'
make  all-am
make[2]: Entering directory '/home/junfei/01_github/libunwind/src'
  CC       os-qnx.lo
os-qnx.c: In function 'callback':
os-qnx.c:44:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(cbi->ip >= segbase && cbi->ip < segbase + info->dlpi_phdr[i].p_memsz)
                ^
  CC       mi/init.lo
  CC       mi/flush_cache.lo
  CC       mi/mempool.lo
  CC       mi/strerror.lo
  CC       aarch64/is_fpreg.lo
  CC       aarch64/regname.lo
  CC       mi/backtrace.lo
In file included from ../include/libunwind.h:7:0,
                 from mi/backtrace.c:29:
mi/backtrace.c: In function 'unw_backtrace':
**../include/libunwind-aarch64.h:243:93: error: 'mcontext_t {aka struct __aarch64_mcontext}' has no member named 'regs'
 #define UNW_BASE register uint64_t unw_base __asm__ ("x0") = (uint64_t) unw_ctx->uc_mcontext.regs;**
                                                                                             ^
../include/libunwind-aarch64.h:248:3: note: in expansion of macro 'UNW_BASE'
   UNW_BASE \
   ^
../include/libunwind-common.h:127:29: note: in expansion of macro 'unw_tdep_getcontext'
 #define unw_getcontext(uc)  unw_tdep_getcontext(uc)
                             ^
mi/backtrace.c:72:7: note: in expansion of macro 'unw_getcontext'
       unw_getcontext (&uc);
       ^
Makefile:4384: recipe for target 'mi/backtrace.lo' failed

**Comment by bregma** [comment]
Should be fixed by PR #551 -- try checking out and building https://github.com/bregma/libunwind/tree/gh-246

**Comment by huige007** [comment]
Hi bregma, I tried the latest commit for branch gh-246, but I got following compile error message:
/opt/qnx/qnx700/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.0.0-ld: .libs/Gperf-simple: hidden symbol `__emutls_get_address' in /opt/qnx/qnx700/host/linux/x86_64/usr/lib/gcc/aarch64-unknown-nto-qnx7.0.0/5.4.0/libgcc.a(emutls.o) is referenced by DSO
/opt/qnx/qnx700/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.0.0-ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:1215: recipe for target 'Gperf-simple' failed
make[1]: *** [Gperf-simple] Error 1
make[1]: Leaving directory '/home/junfei/01_github/libunwind/tests'
Makefile:622: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

I also tried commit, also got following error
/opt/qnx/qnx700/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.0.0-ld: .libs/Gperf-simple: hidden symbol `__emutls_get_address' in /opt/qnx/qnx700/host/linux/x86_64/usr/lib/gcc/aarch64-unknown-nto-qnx7.0.0/5.4.0/libgcc.a(emutls.o) is referenced by DSO
/opt/qnx/qnx700/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.0.0-ld: final link failed: Bad value

is there anything I missed?

**Comment by bregma** [comment]
Hmm, yes, this got broken for QNX 7.0 by  ddfd653. I'll post a fix shortly.

**Comment by bregma** [comment]
...and try it now.

**Comment by huige007** [comment]
compile successfully on my side now.
