### ISSUE TITLE
Workaround for missing libunwind-ptrace.so on Fedora?

### ISSUE THREAD

**Issue by oldiob** [libunwind/libunwind#583]
Not sure if this issue can be solved here.  But it seems that the ptrace variant is missing a shared lib object for quite a time now.

This is highly problematic in my case, since my tool is simply not usable on all RPM based distros.

Is there a known way of fixing this?

Regards,
old

**Comment by bregma** [comment]
If you check out the code from this project and build it locally does it produce a libunwind-ptrace.so file?
