### ISSUE TITLE
Build issue with QNX 

### ISSUE THREAD

**Issue by GuruDlt** [libunwind/libunwind#635]
Hello Team,

I am trying to build unwind library with QNX with below configuration

./configure --host=aarch64-unknown-nto-qnx7.1.0 CFLAGS="-I/home/gta3kor/qnx710/target/qnx7/usr/include -I/home/gta3kor/qnx710/host/linux/x86_64/usr/lib/gcc/x86_64-pc-nto-qnx7.1.0/8.3.0/include -D__QNX__=1 -D__QNXNTO__=1 -D__aarch64__=1 -D__ORDER_LITTLE_ENDIAN__=1234 -D__FLOAT_WORD_ORDER__=__ORDER_LITTLE_ENDIAN__ -D__ORDER_PDP_ENDIAN__=3412 -D__LITTLEENDIAN__=1 -D__ORDER_BIG_ENDIAN__=4321 -D__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__ -D__EXT=1 -nostdinc" LDFLAGS="-L/home/gta3kor/qnx710/target/qnx7/usr/lib"

and I am facing below error:
mi/backtrace.c: In function ‘unw_backtrace’:
../include/libunwind-aarch64.h:245:94: **error: ‘struct unw_sigcontext’ has no member named ‘cpu’**
  245 | # define UNW_BASE register uint64_t unw_base __asm__ ("x0") = (uint64_t) unw_ctx->uc_mcontext.cpu.gpr;
      | 
[buid.log](https://github.com/libunwind/libunwind/files/12739223/buid.log)

can anyone please help me here on priority.

**Comment by GuruDlt** [comment]
this is the where code is falling when it is failing

`#if defined(__FreeBSD__)
# define UNW_BASE register uint64_t unw_base __asm__ ("x0") = (uint64_t) unw_ctx->uc_mcontext.mc_gpregs.gp_x;
#elif defined(__QNX__)
# define UNW_BASE register uint64_t unw_base __asm__ ("x0") = (uint64_t) unw_ctx->uc_mcontext.cpu.gpr;
#else
# define UNW_BASE register uint64_t unw_base __asm__ ("x0") = (uint64_t) unw_ctx->uc_mcontext.regs;
#endif

#define unw_tdep_getcontext(uc) ({					\
  unw_tdep_context_t *unw_ctx = (uc);					\
  UNW_BASE \
  __asm__ __volatile__ (					        \
     "stp x0, x1, [%[base], #0]\n" \
     "stp x2, x3, [%[base], #16]\n" \
     "stp x4, x5, [%[base], #32]\n" \
     "stp x6, x7, [%[base], #48]\n" \
     "stp x8, x9, [%[base], #64]\n" \
     "stp x10, x11, [%[base], #80]\n" \
     "stp x12, x13, [%[base], #96]\n" \
     "stp x14, x15, [%[base], #112]\n" \
     "stp x16, x17, [%[base], #128]\n" \
     "stp x18, x19, [%[base], #144]\n" \
     "stp x20, x21, [%[base], #160]\n" \
     "stp x22, x23, [%[base], #176]\n" \
     "stp x24, x25, [%[base], #192]\n" \
     "stp x26, x27, [%[base], #208]\n" \
     "stp x28, x29, [%[base], #224]\n" \
     "mov x1, sp\n" \
     "stp x30, x1, [%[base], #240]\n" \
     "adr x1, ret%=\n" \
     "str x1, [%[base], #256]\n" \
     "mov %[base], #0\n" \
     "ret%=:\n" \
     : [base] "+r" (unw_base) : : "x1", "memory"); \
  (int)unw_base; })`

**Comment by bregma** [comment]
Try `./configure --host=x86_64-pc-nto-qnx7.1.0 --build=x86_64-linux-gnu` instead of all that cruft. You may not be configuring correctly for cross building.

**Comment by GuruDlt** [comment]
Hi @bregma ,

Thanks for your reply and support.
I have tried as you said and it started throwing errors and stated from below error,

In file included from os-qnx.c:34:
/home/gta3kor/qnx710/target/qnx7/usr/include/sys/link.h:41:8: error: redefinition of ‘struct link_map’
   41 | struct link_map {
      |        ^~~~~~~~
In file included from ../include/dwarf.h:43,
                 from ../include/tdep-x86_64/libunwind_i.h:41,
                 from ../include/tdep/libunwind_i.h:25,
                 from ../include/libunwind_i.h:422,
                 from os-qnx.c:27:
/usr/include/link.h:84:8: note: originally defined here

Please find the build log file respectively and kindly help me with the same.

[build_log_sep28_1.txt](https://github.com/libunwind/libunwind/files/12745908/build_log_sep28_1.txt)

**Comment by GuruDlt** [comment]
Hi @bregma ,

I request you to see once my build environment parameters which I am passing and kindly help me.

:~/clone/TEST_ACP/libunwind$ ./configure --host=aarch64-unknown-nto-qnx7.1.0 --build=x86_64-linux-gnu  CFLAGS="-I/home/gta3kor/qnx710/target/qnx7/usr/include -I/home/gta3kor/qnx710/host/linux/x86_64/usr/lib/gcc/x86_64-pc-nto-qnx7.1.0/8.3.0/include -D=**__aarch64__**=1 -D__QNX__=1 -D__QNXNTO__=1 -D__ORDER_LITTLE_ENDIAN__=1234 -D__FLOAT_WORD_ORDER__=__ORDER_LITTLE_ENDIAN__ -D__ORDER_PDP_ENDIAN__=3412 -D__LITTLEENDIAN__=1 -D__ORDER_BIG_ENDIAN__=4321 -D__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__ -D__EXT=1 -nostdinc" LDFLAGS="-L/home/gta3kor/qnx710/target/qnx7/usr/lib"

[build_log_sep28_2.txt](https://github.com/libunwind/libunwind/files/12748800/build_log_sep28_2.txt)

And with above mentioned configure command, I m facing below error,

mi/backtrace.c: In function ‘unw_backtrace’:
../include/libunwind-aarch64.h:246:37: **error** : **invalid register name for ‘unw_base’**
  246 | # define UNW_BASE register uint64_t unw_base __asm__ ("x0") = (uint64_t) unw_ctx->uc_mcontext.cpu.gpr;
      |                                     ^~~~~~~~
../include/libunwind-aarch64.h:253:3: note: in expansion of macro ‘UNW_BASE’
  253 |   UNW_BASE \
