### ISSUE TITLE
Support installable test suite

### ISSUE THREAD

**Issue by rossburton** [libunwind/libunwind#705]
It's important that libunwind actually works, but in cross-compiled environments it's not possible to run the test suite trivially.

It would be great if there was a way to easily install the test suite, so that in cross environments it can be ran on the target.

**Comment by bregma** [comment]
I will admit that for the QNX port of libunwind at Blackberry we have a local patch to modify upstream to do just this. The interim workaround for supporting `make check` from the build host is to pass a modified driver script to the `--with-testdriver=` argument to configure and have that script use `scp` and `ssh` to copy and run the test on the target.

**Comment by rossburton** [comment]
Our ideal use-case would be:

- build machine installs the tests alongside the library, gets packaged as usual
- test machine install the libunwind-test package and runs the test suite

Currently I'm using this to install the tests:

```
testdir = $(pkglibexecdir)
test_PROGRAMS = $(check_PROGRAMS) $(noinst_PROGRAMS)
test_SCRIPTS = $(check_SCRIPTS)
```
Some (like check-namespace) expect to be ran in the build tree, but also that doesn't check the behaviour so that's not really a problem. The only missing piece right now is the runner, and I can write that by hand.
