### ISSUE TITLE
libunwind with tcmalloc, core at access_mem

### ISSUE THREAD

**Issue by Rick-Stephen** [libunwind/libunwind#718]
Hi, we use libunwind and tcmalloc in x86_64 kernel 3.10, and recently there have been some core problem caused by libunwind stack grabbing.

These stacks probably look like this：
![image](https://github.com/libunwind/libunwind/assets/38900673/a33d5c17-8091-4518-aa2c-864131cf290a)

The corresponding assembly instructions:
![image](https://github.com/libunwind/libunwind/assets/38900673/30be8a26-6a01-4313-9342-71937ed1aa06)

Func backtrace_with_symbols like this:
```
for (i = 0; unw_step(&cursor) > 0; i++) {
        unw_word_t ip = 0;
        unw_get_reg(&cursor, UNW_REG_IP, &ip);
        // user code;
}
```

my env:
libunwind: v1.4.0
tcmalloc: gperftools 2.0
arch: x86_64
kernel: 3.10

**Comment by bregma** [comment]
libunwind v1.4 was released 5 years ago. It's highly likely this has been fixed in more recent releases. Please try a more recent, maintained release and let us know if it resolves your issue.
