### ISSUE TITLE
How to build the libunwind for QNX aarch64?

### ISSUE THREAD

**Issue by ywiyogo** [libunwind/libunwind#73]
I need to build libunwind for QNX ARM-64. I saw the post from Matt Fischer in https://lists.nongnu.org/archive/html/libunwind-devel/2013-04/msg00006.html.

Which parameter options shall I pass to the `./configure`?
If I execute `./configure --host=aarch64-unknown-nto-qnx7.0.0`,  it works. But I get such error messages below during the make build:

```
...
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../include -I../include -I../include/tdep-aarch64 -I. -D_GNU_SOURCE -DNDEBUG -g -O2 -fexceptions -Wall -Wsign-compare -MT aarch64/is_fpreg.lo -MD -MP -MF aarch64/.deps/is_fpreg.Tpo -c aarch64/is_fpreg.c  -fPIC -shared -DPIC -o aarch64/.libs/is_fpreg.o
aarch64/is_fpreg.c: In function ‘_Ux86_64_is_fpreg’:
aarch64/is_fpreg.c:31:21: error: ‘UNW_AARCH64_V0’ undeclared (first use in this function)
   return (regnum >= UNW_AARCH64_V0 && regnum <= UNW_AARCH64_V31);
                     ^
aarch64/is_fpreg.c:31:21: note: each undeclared identifier is reported only once for each function it appears in
aarch64/is_fpreg.c:31:49: error: ‘UNW_AARCH64_V31’ undeclared (first use in this function)
   return (regnum >= UNW_AARCH64_V0 && regnum <= UNW_AARCH64_V31);
                                                 ^
aarch64/is_fpreg.c:32:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:3493: recipe for target 'aarch64/is_fpreg.lo' failed
make[2]: *** [aarch64/is_fpreg.lo] Error 1
```

**Comment by jschmer** [comment]
@ywiyogo Looks like you are trying to build a mix of x86_64 and aarch64. Your error shows that you are compiling the function '_Ux86_64_is_fpreg'. The correct function name would be '_Uaarch64_is_fpreg' when compiling for QNX/aarch64.
Did you have the aarch64-unknown-nto-qnx7.0.0 toolchain in PATH during configure (e.g. something along the lines of 'source ~/qnx700/qnxsdp-env.sh' in your shell session)? If not, then the gcc used is probably the one from the host system, which is the x86_64 toolchain instead of the aarch64 toolchain.

**Comment by alaahl** [comment]
hi, 
how was this resolved?
also,  any idea how to build it for QNX x86_64?
thanks

**Comment by ywiyogo** [comment]
> @ywiyogo Looks like you are trying to build a mix of x86_64 and aarch64. Your error shows that you are compiling the function '_Ux86_64_is_fpreg'. The correct function name would be '_Uaarch64_is_fpreg' when compiling for QNX/aarch64. Did you have the aarch64-unknown-nto-qnx7.0.0 toolchain in PATH during configure (e.g. something along the lines of 'source ~/qnx700/qnxsdp-env.sh' in your shell session)? If not, then the gcc used is probably the one from the host system, which is the x86_64 toolchain instead of the aarch64 toolchain.

Thanks @jschmer for your comment. Nice analysis. However, it's too long ago, and my current PATH is far different than in 2018 :).

**Comment by aamartir** [comment]
Hi @ywiyogo did the suggested changes work for you to compile for QNX aarch64? I'm having similar issues on my end as the ones you described. I appreciate any advice/suggestions.

**Comment by ywiyogo** [comment]
> Hi @ywiyogo did the suggested changes work for you to compile for QNX aarch64? I'm having similar issues on my end as the ones you described. I appreciate any advice/suggestions.

As described by jschmer above, please check your GCC toolchain and your environment again. Make sure your GCC isn't from your x86_64 host.
