### ISSUE TITLE
atomic_fetch_add error

### ISSUE THREAD

**Issue by qhuhuang** [libunwind/libunwind#731]
I use : 
./configure CC=icc CFLAGS="-g -O3 -ip -std=c11" CXX=icc CCAS=gcc CCASFLAGS=-g     LDFLAGS="-L$PWD/src/.libs"

and make,then error
mi/flush_cache.c(56): error: expression must have pointer-to-struct-or-union type
    atomic_fetch_add (&as->cache_generation, 1);
    ^
mi/mempool.c(57): error: expression must have pointer-to-struct-or-union type
    pos = atomic_fetch_add (&sos_memory_freepos, size)

**Comment by bregma** [comment]
Please add the following information to help us analyze the problem.

- OS and environment (eg. GNU/Linux, Musl/Linux, FreeBSD 13)
- version of the compiler (icc)
