### ISSUE TITLE
__libunwind_Unwind_Resume intercepting exception

### ISSUE THREAD

**Issue by joemaniaci** [libunwind/libunwind#759]
**Environment**
- libunwind version: 1.3.1, 1.8.1
- architecture: x86
- OS: Linux version 5.15.0-101-generic (buildd@lcy02-amd64-032) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024
 (Basically I'm running out of a docker container FROM ubuntu:22.04)

**Description**
Have utests that intentionally throw exceptions, and after an upgrade to gcc 11 in our docker image, libunwind started to intercept the exception with a call to __libunwind_Unwind_Resume and cause a segfault. Obviously I'm thinking the gcc 11 upgrade is the culprit, but I have no idea where else to start on this one and it doesn't appear via search that anyone else has experienced this issue. Also, we're currently using libunwind v1.3.1, so I figured, after updating gcc, maybe we need to just update libunwind due to some weird incompatibility. So I tried 1.8.1 and the exact same problem occurred.

This is the configuration from the team that builds libunwind binaries for us. NOTE: The team is still building the binaries with gcc 7.5.0, but there are no linking or dynamic linking issues so I assumed that wasn't the problem.....

    CONFIG_OPTS= \
        --exec_prefix=${LINUX_ROOT} \
        --prefix=${LINUX_ROOT} \
        --host=$(TARGET) \
        --disable-documentation \
        --disable-tests \
        --disable-static \
        --disable-ptrace \
        --disable-coredump \
        --disable-setjmp \
        --disable-cxx-exceptions \
        --enable-debug-frame \
        CFLAGS="-I${LINUX_ROOT}/include" \
        LDFLAGS="-L${LINUX_ROOT}/lib"

The above doesn't appear to have changed in five years, and the guy who decided what to enable/disable is long gone. Going off of the README, it appears we chose to alter things a fair bit.

In terms of consuming the libs, all we're doing is including -lunwind and  -lunwind-x86

The gdb output; You can see that in frame 1, we started to(I guess) catch the exception, and that's when libunwind stepped in and did something?

![image](https://github.com/libunwind/libunwind/assets/4635159/7903ff04-27e1-44b9-a297-ade159f73a23)

As you can see, we wrote our own exception function( framework::Exception, out of curiosity I switched to assembly and put a breakpoint in the constructor of the exception and was able to step all the way through the function and it appears the issue arises when returning from the constructor. I'm a bit rusty, but did our exception function get compiled to just always call _Unwind_Resume every time it returns? Or at least parts of our exception constructor appear to be calling _Unwind_Resume...

![image](https://github.com/libunwind/libunwind/assets/4635159/b3055dd2-427b-4437-b497-7057ae0f133c)

And when I hit next in gdb, I end up here:

![image](https://github.com/libunwind/libunwind/assets/4635159/aea83c09-c796-4642-a032-73f1734856e1)

Which seems to be doing a lot for just being a one liner attribute

    void __libunwind_Unwind_Resume (struct _Unwind_Exception *)
       ALIAS (_Unwind_Resume);

Any help is appreciated, if this is more appropriate for stackoverflow or something like that, just let me know.

**Comment by bregma** [comment]
Did you find a resolution to this?

**Comment by joemaniaci** [comment]
> Did you find a resolution to this?

Yes, I was misled as to how the other team was building things. I built locally and determined libunwind was not at fault.
