### ISSUE TITLE
v1.8.1 setcontext.S:48: Error: undefined symbol SC_FPSIMD_OFF used as an immediate value

### ISSUE THREAD

**Issue by xiedeacc** [libunwind/libunwind#777]
**Environment**
- libunwind version:v1.8.1
- architecture:x86_64
- OS:ubuntu22.04-linx

**Description**
I cross compile for aarch64-linux-gnu-gcc on a linux x86_64 host, but compiler said SC_FPSIMD_OFF not found, I grep source code found, SC_FPSIMD_OFF only take effect on __FreeBSD__ or __APPLE__, so other aarch64 platform how to compile setcontxt.S?

**Comment by bregma** [comment]
`src/aarch64/setcontext.S` is built only for _aarch64-freebsd*_ targets. There is something wrong with how you configured your build.

**Comment by xiedeacc** [comment]
ok, thanks
