### ISSUE TITLE
Thread safety about _write_validate

### ISSUE THREAD

**Issue by hidva** [libunwind/libunwind#786]
https://github.com/libunwind/libunwind/blob/e3f88e8e4b9d2c2df4932a759c269e69dcc3bb97/src/mi/Gaddress_validator.c#L107-L120

Is this thread-safe enough? Consider the following scenario:

1. Thread t1 executes `_write_validate(addr1)`, while thread t2 executes `_write_validate(addr2)` simultaneously.
2. Thread t1 executes `atomic_flag_test_and_set(&_unw_address_validator_initialized)`, changing `_unw_address_validator_initialized` from false to true. At this point, t1 proceeds to execute `_open_pipe`. Meanwhile, thread t2 executes `atomic_flag_test_and_set(&_unw_address_validator_initialized)`. Since `_unw_address_validator_initialized` is already true, t2 directly executes `read(_mem_validate_pipe[0], &buf, 1)`.

**Comment by janvorli** [comment]
When using libunwind in coreclr, we have found this is not safe and in a copy that we use, I had to revert a recent change in this file that has added this mechanism. I have created the #715 issue to track it, so this seems to be a dup of that issue.

**Comment by hidva** [comment]
> When using libunwind in coreclr, we have found this is not safe and in a copy that we use, I had to revert a recent change in this file that has added this mechanism. I have created the #715 issue to track it, so this seems to be a dup of that issue.

Thank you, I will close this issue.
