### ISSUE TITLE
unwind-setjmp not work?

### ISSUE THREAD

**Issue by ygdyang** [libunwind/libunwind#82]
I want to try the unwind-setjmp in Debain 8, GCC 4.9.2
I add a debug printf in the function setjmp() in src/setjmp.c, and rebuild libunwind.
When I run my test program, I didn't see the debug print in consule. It seems the unwind-setjmp is not working.  It is still the setjmp in libc.
And I check the result of cmdline: `readelf -s libunwind-setjmp.so`, no `setjmp` symbol was found.
here is my test program:
```
jmp_buf env; 
int main() 
{
    if (setjmp(env))
        return 1;
    return 0;
}
```
compile:
```gcc -o test_setjmp test_setjmp.c -I  ~/mylib/include -L ~/mylib/lib/  -lunwind-setjmp```

did I make any mistake?

**Comment by djwatson** [comment]
Indeed it looks like it doesn't really work, however, you probably want getcontext() setcontext() instead?
