### ISSUE TITLE
run-coredump-unwind fail when libunwind compiled with gcc 8

### ISSUE THREAD

**Issue by stac47** [libunwind/libunwind#87]
Hello dear maintainer,

As explained in the title, I have a problem building the lib with gcc 8. The problem occurs when running the test __run-coredump-unwind__.
In my case, I have no problem on my ubuntu plateform with gcc 5.4.0, binutils 2.26.1, glibc 2.23.
Now trying in a docker container with a more recent version of gcc (gcc 8.2.0, binutils 2.31.1, glibc 2.27) , I have:
```
root@7497245bf424:/git/libunwind# cat tests/test-suite.log
=============================================
   libunwind 1.3-rc1: tests/test-suite.log
=============================================

# TOTAL: 34
# PASS:  33
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: run-coredump-unwind
=========================

Segmentation fault (core dumped)
FAILURE: start IPs incorrect
FAIL run-coredump-unwind (exit status: 255)
```
I have the exact same issue with libunwind 1.2.1, 1.3-RC1 (even applying the patch #67) and git HEAD.
I also tried with the head of gcc  8.2.1 20180908.
### How to reproduce
```
sudo sysctl -w kernel.core_pattern="core"
docker run -t -i debian:testing /bin/bash
apt-get update && apt-get install build-essential git autotools-dev autoconf libtool
git clone https://github.com/libunwind/libunwind.git
cd libunwind
./autogen.sh
./configure
make
make check
```
### Investigation
Digging further, it seems that libunwind is a not able to step the 4 expected frames leading to an error.

If I run run-coredump-unwind without the -testcase option passed to test-coredump-unwind script, I get this in the working case:
```
:~/opensource/libunwind/tests$ ./run-coredump-unwind
Segmentation fault (core dumped)
        ip=0x00400890 proc=00400890-004008a1 handler=0x00000000 lsda=0x00000000
lt-test-coredump-unwind: step
lt-test-coredump-unwind: step done:1
        ip=0x004008bd proc=004008b0-004008d2 handler=0x00000000 lsda=0x00000000
lt-test-coredump-unwind: step
lt-test-coredump-unwind: step done:1
        ip=0x004008ca proc=004008b0-004008d2 handler=0x00000000 lsda=0x00000000
lt-test-coredump-unwind: step
lt-test-coredump-unwind: step done:1
        ip=0x004008fc proc=004008e0-00400906 handler=0x00000000 lsda=0x00000000
lt-test-coredump-unwind: step
lt-test-coredump-unwind: step done:1
signal:11 address:0x7f3d6f85fba0 ip:0x7f3d6f2301c6
/home/ubuntu/opensource/libunwind/tests/.libs/lt-test-coredump-unwind[0x4017b8]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f3d6ee8d4b0]
/home/ubuntu/opensource/libunwind/src/.libs/libunwind-x86_64.so.8(_Ux86_64_dwarf_find_unwind_table+0x146)[0x7f3d6f2301c6]
/home/ubuntu/opensource/libunwind/src/.libs/libunwind-coredump.so.0(_UCD_find_proc_info+0xc9)[0x7f3d6f43fa09]
/home/ubuntu/opensource/libunwind/src/.libs/libunwind-x86_64.so.8(+0x9987)[0x7f3d6f22b987]
/home/ubuntu/opensource/libunwind/src/.libs/libunwind-x86_64.so.8(+0xc1e7)[0x7f3d6f22e1e7]
/home/ubuntu/opensource/libunwind/src/.libs/libunwind-x86_64.so.8(_Ux86_64_get_proc_info+0x11)[0x7f3d6f226561]
/home/ubuntu/opensource/libunwind/tests/.libs/lt-test-coredump-unwind[0x401231]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f3d6ee78830]
/home/ubuntu/opensource/libunwind/tests/.libs/lt-test-coredump-unwind[0x401499]
```
And in the non-working case:
```
/git/libunwind/tests# ./run-coredump-unwind
Segmentation fault (core dumped)
        ip=0x56143448d2b0 proc=56143448d2b0-56143448d2b1 handler=0x00000000 lsda=0x00000000
test-coredump-unwind: step
test-coredump-unwind: step done:0
test-coredump-unwind: stepping ended
```
Hence the following question: why the return code of unw_step is 0 ?

Thanks in advance for your help,
Regards,
Stac

**Comment by djwatson** [comment]
gcc is probably generating a different number of frames than previous gccs.  Clang has a similar issue.  Everything should still work ok, but it means many of the tests don't pass.  I don't have a great solution to this yet.

**Comment by psandana** [comment]
@djwatson why is this closed? I have the same issue with GCC 9.2.0. Is this resolved?

**Comment by djwatson** [comment]
I'm assuming what's happened is that the function calls in the crash program got inlined in newer GCCs, and hence there are fewer frames to walk.  There's already a handful of fixes to try and work around this, but it's unlikely we will ever come up with a solution that will work for all compilers.

If you want to submit more fixes for more recent GCC's, I'd be happy to accept them, but generally the failure of this (and many of the other) testcases doesn't indicate a bug in libunwind itself.

**Comment by psandana** [comment]
I'm not expert in compilers, but wonder if we can just disable in-lining for the test compilation only. I will think about how to contribute to this, despite I'm just starting with libunwind.
Thanks!
