### ISSUE TITLE
Re-enable per-thread dwarf cache 

### ISSUE THREAD

**Issue by djwatson** [libunwind/libunwind#9]
Has been broken for a long time, currently doesn't use TLS nor locks, and just isn't thread safe. 

#8 is an attempt to fix.

One complication here is that TLS, at least in the glibc implementation, allocates memory and sometimes takes locks, making it not thread safe.   For some users this might not matter, but can't be the default.

**Comment by bertwesarg** [comment]
You meant "isn't signal safe", right? Also, the current code does not allow to enable the per-thread cache at all. So nothing is broken. The current situation with the global cache and its lock isn't signal friendly either, right?

**Comment by bertwesarg** [comment]
Please also note, that glibc should only dynamically allocate memory for TLS variables, if the DSO is also dynamically loaded, i.e., via dlopen. TLS variables in the application and the initial DSOs should be allocated right at thread creation time, which should not be in a signal context.

**Comment by djwatson** [comment]
The current master is not thread-safe if UNW_CACHE_PER_THREAD is specified, as it doesn't use thread-local storage, and the lock is only acquired for UNW_CACHE_GLOBAL.

Correct, the proposed #8 is only signal-unsafe if libunwind is used in a shared library. (I recall it being an issue of allocation at first use for all shared libraries, not just dynamically-loaded, but I could be wrong).  There was a proposed fix to glibc at one point.

Anyways I'd propose we fix the set_cache_size issue, and commit it with UNW_CACHE_GLOBAL as the default.

**Comment by bertwesarg** [comment]
I'll repeat: "the current code does not allow to enable the per-thread cache at all", i.e,

```
unw_set_caching_policy (unw_local_addr_space, UNW_CACHE_PER_THREAD);
```

will fallback to UNW_CACHE_GLOBAL. Because of this code in libunwind_i.h:

```
#ifdef HAVE___THREAD
  /* For now, turn off per-thread caching.  It uses up too much TLS
     memory per thread even when the thread never uses libunwind at
     all.  */
# undef HAVE___THREAD
#endif
```

**Comment by djwatson** [comment]
Ah, yea I missed that.  Indeed it's not currently broken.

**Comment by bertwesarg** [comment]
Can we somehow make it possible to trigger the TLS access manually, where the caller can ensure that he is not in the signal context. In my use case I know, when the thread is created. Does a call to unw_init_local suffice for this?

**Comment by djwatson** [comment]
I don't think unw_init_local currently suffices, but we could make it do so, yes.

**Comment by bertwesarg** [comment]
Would a call to `unw_get_accessors(unw_local_addr_space)` suffice, as it calls `tdep_init`?

**Comment by bertwesarg** [comment]
A second possibility, is that a user creates for each thread its own copy of `unw_local_addr_space`. Than one would only need to disable the locking for the cache. But I'm not sure, if libunwind would handle these per-thread local address spaces like _local address_ spaces, as I find many places in the code bas, which test for the `unw_local_addr_space` or use it directly.

**Comment by djwatson** [comment]
a call to unw_step is definitely sufficient, I haven't checked unw_get_accessors.  Yea unw_local_addr_space is probably tricky, you'd loose some of the inlining.

**Comment by djwatson** [comment]
merged, use --enable-per-thread-cache
